# A diferença entre aprendizado e aquisição {-}

É necessário diferenciar o aprendizado de uma língua da aquisição de uma língua. Quando você diz que quer saber falar ou compreender uma língua, você afirma querer adquirir uma língua. A aquisição implica na habilidade prática de compreender e de se comunicar. O aprendizado implica em saber sobre a língua, e não ela mesma.

Por exemplo, eu sei utilizar o verbo "ser". Sei também falar sobre o verbo "ser". São coisas diferentes. Quando estudamos gramáticas, regras e outras coisas do gênero, não estamos aprendendo a língua exatamente, mas sobre a língua.

Existe uma diferença entre saber dissecar uma língua e de fato dominá-la e poder navegar por ela. Se quando leio grego preciso esmiuçar o texto para compreender as declinações e a função sintática de cada palavra, então o meu acesso ao grego não é direto. Eu só acesso o grego por meio de um cálculo, de um raciocínio esmiuçante. E isso é válido, é digno, ainda mais porque, em se tratando do grego antigo, não tem ninguém que o fale (salvo alguns padres ortodoxos e helenistas, creio eu).

Mas você não quer isso para falar inglês ou outra língua contemporânea. Você quer rapidez, quer falar sem ter que calcular, ou calculando muito pouco.

Por isso eu sou contra o aprendizado da língua *pela* gramática. Não sou *contra* a gramática -- ela tem seu lugar e vamos tratar dela --, mas se você aprende língua pela gramática, você não tem um acesso direto à língua, e sim precisa calcular e arquitetar suas frases de forma exageradamente cerebral. É como ter que pagar pedágio: antes de qualquer avanço é necessário parar.

A alternativa é a aquisição. Para adquirir uma língua, é necessário imersão. Vamos tratar disso posteriormente.

## Resumo

-   yadda yadda
