# Como aprender uma língua {-}

Aprender línguas é um processo estranho, e de certo modo paradoxal. Língua se aprende através da compreensão: você aprende uma língua quando você a entende. Isso pode parecer um problema: como vou aprender uma língua se para aprender tenho que compreendê-la? É como se o objetivo final fosse um pré-requisito, o que o torna completamente inalcançável.

Sim, para aprender uma língua é necessário compreendê-la. Mas isso não deve servir como um sinal de "pare" ou um motivo de hesitação, mas nos fornecer uma ideia do que nos espera: o objetivo da jornada é a própria jornada. O meio e o fim têm mais ou menos a mesma cara, e as práticas pouco mudam em diferentes partes da trajetória.

Vamos nos debruçar agora sobre como aprendemos de fato uma língua.

## Motivação {-}

Primeiro de tudo, para aprender uma língua você só precisa passar tempo com ela. Quanto mais tempo você passar na língua, prestando atenção e (mais importante) se divertindo, mais você vai aprendê-la. [Isso obviamente vai exigir motivação][A motivação]. Aprender uma língua leva tempo. Para alcançar algo mais próximo da perfeição (que é de fato inalcançável) são necessários anos. Então é necessário ter um bom motivo pra fazer isso. Mas mesmo que você pare na metade do caminho, não terá sido inútil. Não caia na ladainha perfeccionista de que "não saber perfeitamente é equivalente a não saber nada". Conhecimento de uma língua é útil em todos os níveis: se você sabe muito ou se você sabe pouco, é sempre melhor do que não saber coisa nenhuma. 

## Imersão {-}

Mas pra aprender uma língua você [precisa entendê-la em algum grau][Como adquirir uma língua]. Todavia, se você estiver entendendo tudo, 100%, você não está aprendendo nada, o conteúdo está fácil demais. [Não é proveitoso seja tão fácil, mas também não é bom que seja tão difícil que você só entenda duas palavras de cem.][Melhores conteúdos para aprender uma língua].

Esse conteúdo será utilizado para **imersão**. Ele deve ser algo que seja interessante para você e que te desafie. Os recursos para aprender línguas que têm maior custo-benefício são as mídias audiovisuais: jogos, filmes e séries. Documentários e noticiários também podem ser úteis, mas estes costumam ser mais difíceis de compreender. Você precisa passar muito tempo com a língua, assistindo, jogando, ouvindo. **Adquire-se uma língua pela imersão, e imersão é passar tempo com a língua**. Jogos são os mais úteis porque eles exigem que você preste atenção, e você pode se divertir mesmo se não estiver entendendo tudo. Se você não gosta de jogos, filmes e séries têm utilidade inegável. Livros e podcasts também são ferramentas válidas para o aprendizado, principalmente os que são elaborados para leitores e ouvintes de níveis específicos de desenvoltura no idioma ("leitura nivelada").

O processo de imersão, assim como o de começar a falar na língua-alvo, pode causar certa ansiedade e insegurança. No capítulo sobre [ansiedade de exposição][Ansiedade de exposição] eu trato um pouco mais a respeito dos sentimentos, dúvidas e práticas ruins comuns entre aprendizes de idiomas.

Algumas línguas são muito diferentes e portanto muito difíceis. Isso torna a imersão mais desconfortável. Por conta disso, considere a seção logo abaixo, nesta mesma página, sobre as [ferramentas auxiliares][Ferramentas auxiliares] que nos servirão de suporte nesse processo. A imersão sem elas pode ser muito complicada, então é recomendado que você as utilize. Cuidado, porém, para não utilizá-las para ficar "se preparando eternamente". Não postergue a imersão para aprender palavras isoladamente.

Se você está aprendendo uma língua que usa outro sistema de escrita, como russo ou grego, é importante que você aprenda logo (e talvez primeiro) esse modo diferente de escrever. Aprender sistemas de escrita não é difícil, e provavelmente pode ser a parte mais fácil da língua. [Sistemas de escrita][Há uma página neste site que mostra justamente isso]. A exceção, óbvio, são as línguas que usam ideogramas (como japonês e mandarim). No caso destas você vai ter que fazer um esforço paralelo para aprender os símbolos individuais. Existem sistemas desenvolvidos para aprender esses modos de escrever. Se este for o seu caso, sugiro que faça uma pesquisa para encontrar um que se adeque às suas necessidades.

## Características do conteúdo para imersão  {-}

Imersão é passar tempo com a língua, mas é necessário também prestar atenção no conteúdo que você está utilizando para este propósito. Abaixo discute-se a respeito de diferentes tipos de conteúdo para imersão.

### Audiovisual: jogos, filmes e séries {-}

Os jogos não devem ser multiplayer, mas sim de um único jogador e voltados para enredo.^[Excessão: um jogo multiplayer em que quase todo mundo nele fale a língua que você quer aprender. Hoje em dia encontrar esse tipo de coisa está cada vez mais difícil.] Jogar FIFA em inglês com um amigo não vai te ajudar em nada para aprender esse idioma. O mesmo se aplica a ficar horas jogando Minecraft sozinho. Mais vale que você jogue um jogo cheio de história, como Metal Gear, God of War, The Last of Us, The Witcher 3, entre outros. Contudo, é importante que ele seja interessante para você; que o enredo, que a história te provoque curiosidade, esse tipo de coisa. 

Tanto os jogos quanto os filmes e as séries **devem ter tanto dublagem e legenda na língua que você quer aprender**. Não coloque a legenda em uma língua que você sabe, nem o áudio. Não tire a legenda para "[se desafiar a treinar suas habilidades de escuta][Tirar legendas]". Se algo te ajuda a entender mais a língua que você quer aprender, **sem sair da língua**, tanto melhor.

Conteúdo audiovisual é extremamente útil porque as cenas vão te ajudar a entender o que as palavras querem dizer. O contexto vai revelar o significado do que você não compreende. Se você insistir nisso, você logo verá resultados.

### Livros e Podcasts {-}

A leitura também é útil, embora seja difícil encontrar textos que sejam amigáveis ao nível de um iniciante. Leituras niveladas são a solução, neste caso. Pode ser que não haja tanta leitura nivelada disponível pro idioma que você quer aprender (caso você queira aprender um idioma menos "famoso", como, digamos, a língua maltesa), mas é fácil encontrar conteúdo para línguas como inglês, francês, espanhol, russo, entre outras. Recomendo sites como o [English e-Reader](https://english-e-reader.net/findbook/) (apenas para o inglês) e o [Lingua.com](https://www.lingua.com/) (para diversas línguas). Falo mais sobre isso na seção sobre [Livros]. Você pode encontrar mais coisas pesquisando online em inglês, usando as palavras chave "[LÍNGUA] graded readers". Por exemplo: "russian graded readers", ou "italian graded readers".

Tudo o que é verdadeiro para a leitura, também o é para podcasts. Você pode encontrar podcasts nivelados por aí. Se você pesquisar coisas como "Beginner English Podcast" (Podcast para iniciantes no inglês) ou "Beginner French Podcast" (Podcast para iniciantes no francês) você encontra podcasts para iniciantes nas línguas do seu interesse. [Podcasts][Os podcasts variam em qualidade], e existem podcastas didáticos ruins e podcasts didáticos bons.

## Ferramentas auxiliares {-}

Pode ser que só a leitura e/ou os podcasts esteja disponível para você, caso você não tenha acesso a conteúdo audiovisual, seja por não ter acesso a serviços de streaming, ser deficiente visual ou simplesmente achá-los insuportáveis. Se esse for o seu caso, você também precisará suplementar sua prática com alguma ferramenta para aumentar o seu vocabulário. Para este propósito, o [Anki][O uso de aplicativos] é perfeito. [Neste link][O uso de aplicativos] eu explico mais sobre o que o Anki é e como como utilizá-lo.

Entretanto, eu não recomendo que você considere o Anki _apenas_ como um suporte alternativo, voltado para pessoas que não utilizarão mídias audiovisuais. Eu acho que _todos_ podem se beneficiar em utilizá-lo. Ele pode acelerar _muito_ o seu processo de aprendizado. Você vai descobrir logo, principalmente com o uso recorrente, que ele é um pouco chato, mas extremamente útil. [Ele por si só não basta][A interação entre repetição espaçada e imersão], mas é inegável que acelera o processo. 

## A habilidade da fala {-}

[Quanto à habilidade da fala][O desenvolvimento da fala], é simples: a fala depende da sua compreensão. Se você quiser falar bem, você deve primeiro ser capaz de compreender bem. Quando você for capaz de entender livros inteiros, você provavelmente estará numa boa condição para trabalhar a fala. Claro, você pode fazer isso antes, mas:

- Na musculação, você treina um músculo e ele cresce. A fala não procede da mesma forma. Sua fala não melhora simplesmente por você praticar falar com frequência. 
- A melhor forma de melhorar a sua fala (e a sua escrita) é pela leitura e pela escuta.

A fala é resultado do que você consome, e você deve consumir tanto em quantidade como em qualidade. Falar cedo demais pode resultar em vícios, assim como vícios podem resultar de falar com pessoas que falam errado.

Para te ajudar a desenvolver a fala, é bom ter um [language parent][Prática: _language parents_], que é um tutor que vai se dedicar a falar com você na habilidade. Atenção: tutor, e não "um colega". Se falar cedo demais pode resultar em vícios, isso pode igualmente acontecer se você falar com alguém que está no mesmo nível com você, ou abaixo, ou apenas um pouco acima. Você quer alguém que realmente domine o idioma. Cabe _pagar_ alguém para conversar contigo. Aqui se encontra [o valor dos professores e dos cursos, e também as ressalvas a respeito dos mesmos][Cursos e professores].

## O papel da gramática {-}

Não se preocupe com gramática. Ela tem o seu lugar, mas você pode deixá-la para depois. O motivo disso é o seguinte: [a gramática serve para firmar o que está bambo][O papel da gramática]; serve para aperfeiçoar o que já existe. Uma outra utilidade dela é "espremer o restinho do suco da fruta". Você precisa ter substância, e muita substância, para poder dar pra ela alguma estrutura; você também não precisa se preocupar em extrair até a última gota enquanto a sua fonte ainda te rende litros com facilidade. Focar-se em gramática desde o princípio é colocar a carroça na frente dos bois. Se você não tem areia, para que você vai querer um molde? Deixe para utilizar o molde para quando você tiver areia de sobra. 

O que é essa areia? Horas e horas -- **centenas** de horas -- de exposição a conteúdo na língua que você aprendeu. 

## A importância do interesse {-}

E qual é o melhor tipo de conteúdo? Aquele que é interessante para você. Como foi falado anteriormente, o conteúdo não deve ser nem difícil demais, nem fácil demais -- mas se ele for muito difícil e mesmo assim muito interessante, continue com ele.

## Conclusão {-}

Isso é tudo o que você precisa saber. Caso julgue necessário, siga a leitura do site, ou explore os links dessa página conforme seu interesse. Você não precisa lê-los sequencialmente. Cada uma das questões aqui expostas será destrinchada minuciosamente nas próximas páginas.

Vá. Mergulhe. Imerja-se na língua que você quer aprender. **Não fique se preparando eternamente**. [Não existe isso de "estar preparado" para a imersão][Ansiedade de exposição]. É a imersão que te prepara para ela, e se você quer falar, é ela que vai te dar essa capacidade. Use uma ferramenta como o Anki para te ajudar a amplificar o seu vocabulário e facilitar a imersão. Porém **cuidado**: não deixe que tais ferramentas se tornem substitutos.

As páginas a diante são uma exposição mais detalhada de como fazer isso, começando por uma exposição geral do que você pode esperar encontrar neste site. 
