# O papel da imersão {-}

Para aprender uma língua é necessário viver uma língua, viver _numa_ língua. É preciso criar memórias, lembranças. É preciso associar palavras com acontecimentos, com filmes, com séries, jogos, cenas, interações com pessoas queridas, com inimigos, com estranhos. Convém fazer amigos, convém conhecer a cultura que vem com a língua.

A imersão é a via régia da aquisição de uma língua. Antigamente, para praticar imersão havia duas alternativas: ou você vai para um campo ou território onde só se pode falar a língua, como um curso onde se pratica a imersão, ou você viaja pra o país onde se fala a língua.

O primeiro caso tem o defeito de você ter interações majoritariamente com pessoas que também estão aprendendo o idioma. Isso é problemático porque você pode ser afetado pelos vícios de linguagens dessas pessoas. O ideal é tratar direto com professores com um nível realmente, verdadeiramente avançado, ou com nativos. Os professores podem não falar tão bem quanto os nativos e podem ter vícios metodológicos, e os nativos podem não ter uma didática (ou paciência) como os professores. O ideal seria um professor nativo sem vícios metodológicos, mas unicórnios são raros.

O segundo caso (para outro pais) é caro e só quem tem dinheiro pode segui-lo, e dificilmente por muito tempo.

Mas desde os anos 90 uma tecnologia maravilhosa se introduziu (e até se intrometeu) nas nossas vidas: a Internet.

Graças à Internet é possível praticar imersão direta seja conversando com nativos online, seja lendo textos originais, assistindo filmes e séries e jogando jogos digitais. Esses são os melhores recursos que podemos utilizar.

A aquisição se dá pela imersão. Quando e como é que se adquire uma língua? Quando se a compreende. Mas como posso compreender uma língua se não a compreendo? Continuando a não compreender e insistindo. 

Nisso o contexto ajuda muito. Se assisto um filme, uma série, leio um livro, jogo um jogo, e vejo uma palavra que não conheço sendo utilizada frequentemente em um mesmo contexto, posso então _deduzir_ o significado dessa palavra pelas situações em que ela é utilizada. No início isso é difícil, mas com o tempo isso vai ficando cada vez mais fácil.

E é, verdadeiramente, um processo mágico. Você não percebe que está aprendendo. É como passar por uma aventura e perceber-se tendo crescido após o seu término de uma forma que não era possível durante o processo.

Quando resolvi aprender russo, depois de aprender o alfabeto (e aprender alfabetos é mais fácil do que parece) e umas quinhentas palavras usando aplicativos, resolvi jogar The Witcher 3. Não conseguia entender quase nada, nem da interface gráfica do usuário, nem do que os personagens falavam. O jogo estava incompreensível. Parei de jogá-lo pois outro jogo me chamou a atenção: Metro Exodus. Comecei a jogá-lo, igualmente sem compreender o que estava sendo dito. Mas com o tempo eu compreendi o que algumas expressões significavam. 

_Давай!  Давай! Пойдём! Давай в машину!_
_Davái! Davái! Poidyôm! Davái v mashínu!_
_Vai, vai, vamos! Entre no carro!_

O contexto em que essas frases eram ditas me permitiam compreendê-las melhor.

Joguei o jogo até o final. Não foi difícil pois o jogo era muito, muito divertido, de modo que eu praticamente não me importava em não entender tudo do que estava sendo dito. Quando terminei o jogo fui logo jogar The Witcher de novo. Algo peculiar aconteceu: eu agora compreendia mais de 50% do que era dito no jogo. Eu não percebi o aprendizado acontecendo; foi tudo inconsciente. Quando me vi, era capaz de entender. Junte a isso alguns filmes russos (Kalashnikov, Sobachnuy Tserdse), séries (Better Than Us, Cidade dos Mortos) , a leitura de contos (Dostoievski, Tchekhov, Gogol), conversas com nativos online (no Preply e no Discord), 

Foi exatamente assim que eu aprendi inglês. Foram outros jogos: Neverwinter Nights, Age of Mythology, Oblivion, Flyff; outras séries (The Big Bang Theory, Breaking Bad); outros filmes (Let me in, My Name is Khan); conversas com nativos (no 9gag, no Omegle e turistas que vez ou outra encontrei); histórias como The Catcher in the Rye e Game of Thrones. Sou, eu diria, plenamente fluente no inglês de tanto ter-me exposto. Depois de tanto ouvir e tanto ler, começar a falar foi como desenferrujar: sim, eu não costumava falar, mas eu sabia todas as palavras. Era questão de tirar a poeira da língua, o que me foi proporcionado em um curso que adentrei para poder começar a dar aula em um escolas de inglês, mas conversas com nativos teriam funcionado igualmente bem. 

Não sou fluente no russo, mas por quê? Por questão de tempo. Fiquei anos aprendendo inglês assim, e me dediquei deste modo ao russo por cerca de um ano e meio. Mas aonde é que isso me levou? Não consigo ler Crime e Castigo no original e entender tudo, mas consigo assistir filmes e entender mais de 90%; se eu tivesse que me mudar pra Rússia amanhã, meu russo estaria repleto de erros, mas eu conseguiria entender todo o russo do cotidiano (ficando-me vedado o russo rebuscado que se utiliza em pronunciamentos políticos), e em pouco tempo, acredito eu, seria capaz de suturar minhas faltas no idioma.

Isso sem estudar gramática. Ora, como é que é possível alcançar a fluência sem dominar a gramática? Eu não vou falar tudo errado se eu agir deste modo?

Esse é o próximo tópico.

**Resumo**
