# Melhores conteúdos para aprender uma língua 

- [ ] Explicar a respeito do I+1 e do seu lugar

Conteúdo audiovisual -- séries, filmes e jogos digitais --, então, tem um certo privilégio. Ele apresenta as palavras em _cenas_, e as _cenas_ nos ajudam a entender o que elas significam. Eu acredito pessoalmente que os jogos digitais^[especificamente os jogos para um só jogador e ricos em enredo; jogar FIFA ou League of Legends nunca será tão útil para aprender um idioma como Metal Gear, Heavy Rain, Warcraft etc.] são os mais úteis meios de adquirir uma língua, já que eles exigem mais da sua atenção do que séries e filmes.

Assim, eu categorizaria do como os mais fáceis de entender os jogos, e os mais difíceis de entender os livros e podcasts. Do mais fácil para o mais difícil, eu os classificaria da seguinte forma: jogos; filmes e séries; podcasts e livros. E lembre-se: **você não quer se desafiar desnecessariamente. Você aprende mais quando você entende mais, então você não precisa se desafiar mais do que o necessário**.

Mas tem gente que não gosta, e tem gente que não tem acesso a conteúdo audiovisual. _Se você não gosta, eu te aconselho a fazer uma forcinha_, mas se você não tem acesso (seja pelo motivo que for), é possível trabalhar com podcasts e livros. Esse tipo de prática precisa ser apoiado por algum sistema auxiliar. Na verdade, até mesmo quem vai se apoiar completamente em conteúdo audiovisual pode se beneficiar muito desses sistemas auxiliares. Esses são os "sistemas de repetição espaçada". Também é possível utilizar livros e histórias niveladas. Eu pessoalmente acho quer ler contos e histórias curtas é muito proveitoso. Falo mais sobre isso  e dou alguns exemplos em [O uso da leitura nivelada].
