# A motivação {-}

A importância da motivação é inegável. Considere a relevância dela no nosso objetivo de aprender uma língua: sem ela não é possível nem começar, nem continuar por tempo suficiente para obter resultados. 

O que fundamenta nossa decisão de fazer algo? Isto é, por que é que queremos buscar este ou aquele objetivo? O impacto das nossas buscas sobre as nossas vidas se dão em função não apenas das nossas ações, mas também das intenções por trás delas. 

Não acredito na ideia de "fracassar" em aprender uma língua. Podemos apenas usar métodos ineficientes ou até desistir depois de um certo período de esforço, mas o pior resultado disso é apenas ter alcançado um certo patamar no idioma, aquém do desejado. Não existe fracasso absoluto, apenas modulação de expectativas e usos de métodos mais ou menos eficientes.

Mesmo que não cheguemos à fluência absoluta em uma língua, ainda assim teremos alcançado _certo_ nível de compreensão, _certo_ nível de habilidade de comunicação. A fluência e a proficiência são objetivos muito atraentes, mas não são obrigatórios. A aspiração à total fluência pode ser fruto de necessidade e interesse, mas pode igualmente fruto de um indevido perfeccionismo.^[Não falo isso para dizer que não se deva aspirar à fluência, nem que esse método não pode te levar a tal conquista. O método que aqui é divulgado pode te levar à fluência em qualquer língua, desde que os recursos para imersão (tema a ser tratado nos próximos capítulos) nela existam. Inúmeras pessoas adquirem proficiência em outras línguas por meio deste método; eu mesmo sou uma dessas. Apenas reitero que um domínio de uma língua que não chega à fluência não é um domínio inválido: você não é obrigado a falar igual um nativo em todas as línguas que você se dedicar a aprender, principalmente se você tiver a intenção de aprender múltiplas línguas. Muitas comunidades de poliglotas na Internet cultivam uma relação obsessiva com o aprendizado de línguas, objetivando a absoluta fluência, às vezes em múltiplas línguas, às vezes motivados apenas por "se provarem para os outros". Tais intenções levam ao estresse e à desistência mais frequentemente do que à fluência de fato.] Se você quer aprender a língua por um motivo que não exige que você se torne fluente -- e nada mais -- não tem porque você se obrigar a alcançar a fluência, nem a julgar que o seu conhecimento da língua é inválido só porque você a sua habilidade nela não é perfeita.^[A própria ideia de fluência não é fixa, mas dependente de contexto. Pense, por exemplo, em um assunto que você gosta. Você provavelmente poderia falar dele na sua língua com fluência, e você provavelmente conhece inúmeros termos específicos relacionados a ele. Agora pense em um assunto que não é tanto do seu interesse, que seja complexo e que você não domine. Mesmo na sua língua natal, é normal que você não conheça o vocabulário pertinente a este assunto. O mesmo se aplica às línguas estrangeiras: se você não se interessa por culinária, talvez você seja perfeitamente capaz de falar fluentemente a respeito de mecânica quântica nesta língua, mas gaguejar na hora de ensinar alguém a fazer um macarrão.]

O que deve te levar à fluência não é um senso de obrigação em "chegar ao fim da língua", como se ela fosse uma lista de afazeres, mas sim um interesse (ou necessidade) sinceros nela e na cultura que vem com ela associada.

Dito isso, vamos tratar do _tempo_ que você pode esperar levar para aprender a língua.

---

Se você for no YouTube, você facilmente poderá encontrar vídeos como "aprendi a falar italiano em uma semana". Não vou negar: é possível aprender um nível relevante de italiano em uma semana. Contudo, sendo realista, isso não vai muito além da capacidade de ler alguns trechos bem simples, falar superficialmente sobre alguns assuntos e dizer algumas outras coisas básicas. Como falamos português e o italiano é uma língua "irmã" da nossa, pode ser que consigamos aprender a _compreender_ muito italiano bem rápido, mas a compreensão sempre antecede a produção em uma língua.

Se o que você vai falar é pré-planejado, é muito fácil aprender a falar. Muitos desses vídeos que dizem "ter aprendido uma língua em uma semana" (talvez todos) demonstram uma habilidade que é apenas _aparente_: tais vídeos seguem um script.

A seriedade da questão começa no fato de que falar uma língua, de verdade, significa poder se comunicar nela em um ambiente **não controlado**. Isso não quer dizer que é necessário fazer isso com perfeição -- mas se tudo o que você faz com uma língua só pode ser feito com muito ensaio, então alegar fluência nela não é apropriado. Você pode falá-la em certo grau, mas é importante ser honesto. Se alguém se diz fluente, esse alguém deve ser capaz de improvisar e de levar uma conversa sobre múltiplos diferentes assuntos sem precisar de planejamento ou ensaio.

Começo assim para dizer que adquirir uma língua leva tempo. Alguns dizem que você pode ser fluente em seis meses. Talvez seja verdade, principalmente se você vive num país em que se fala essa língua. Mas, sendo sincero, a menos que seja uma língua muito parecida com a que você já fala (como o espanhol para nós falantes de português)^[O que torna uma língua mais ou menos difícil de para um estudante são duas coisas: 1. A semelhança desta língua com a(s) que ele já fala; 2. A quanto conteúdo nessa língua ele tem acesso. Ou seja, aprender inglês e espanhol é mais fácil para nós falantes de português do que grego ou mandarim -- estas línguas são ou muito diferentes da nossa ou têm pouco conteúdo disponível ao nosso acesso, ou ambos. Claro, tal escassez de conteúdo pode ser remediada _indo morar lá_ onde se fala essa língua, mas isso não é factível para a maior parte das pessoas.], provavelmente vai levar mais de um ano. Por baixo.

Logo, isso quer dizer alguma constância. Talvez não todo dia (embora seja melhor se assim for), mas algumas vezes por semana. "Quase todo dia" não é uma medida objetiva, mas é uma ótima medida. É necessário estudar algo entre "todo dia" e "quase todo dia". Mas tenha calma: estudar línguas contemporâneas (em comparação com línguas como latim, grego e sânscrito) pode ser muito mais leve e mais divertido do que ler pilhas de livros de gramática e de exercícios repetitivos.

Pra manter essa constância é necessário um bom motivo. A disciplina é mais importante do que a motivação, mas a motivação dá sentido à disciplina. Faria sentido empenhar-se tanto para aprender uma língua que você não gosta? Uma língua de um povo e de uma cultura que não te provoca nenhum interesse? Digamos que você esteja aprendendo uma língua só porque alguém exige isso de você. É óbvio que você pode conseguir, mas vai ser um processo desgastante. Você vai precisar de muita cobrança externa pra alcançar resultados que seriam mais facilmente alcançados na presença de interesse genuíno. Vai ser chato. Talvez você faça um curso, mas você vai querer parar se não estiver gostando -- é natural. Logo, gostar é muito importante.

E o que te faz gostar da língua? É a música? É o povo? É que você tem um amigo que fala essa língua? É que alguém da sua família, alguém que lhe é caro, veio de outro país e só consegue falar nessa língua, e você quer se comunicar com essa pessoa? São as oportunidades de trabalho? De viagens?

Geralmente cultura é um motivador muito forte. Muitas pessoas aprendem inglês por causa do mercado de trabalho. Aprender inglês faz com que seja possível comunicar-se com pessoas ao redor do mundo todo, e nos dá acesso a um volume de literatura muito maior do que qualquer outra língua -- pois, sem contar a própria literatura anglófona, quase tudo se traduz para o inglês. Isso não é verdade no caso do alemão, mandarim, russo ou sânscrito. 

Por que então alguém iria querer aprender alemão, mandarim, russo ou sânscrito? Deve ser um motivo pessoal, não? Algo como _essa língua é a mais bela do mundo pra mim_, ou então _eu adoro a cultura desse país_. _Eu gosto da história, da literatura, da filosofia, da religião que é escrita nessa língua. Quero poder ler Dostoiévski, ou Goethe, ou o Tao Te Ching no original. Quero me mudar pra esse país, quero falar com as pessoas de lá, quero ter acesso a informação que de outro modo eu não teria._

Talvez você precise aprender uma língua por causa do mercado de trabalho, mas que diferença tem o mercado de trabalho em comparação com aquela pessoa que exige, cobra e te importuna para aprender uma língua pela qual você não se interessa? _Meu pai quer porque quer que eu aprenda francês, e pra mim francês é incrivelmente chato_, alguém pode pensar. Ora, que diferença tem isso de _meu trabalho exige que eu aprenda inglês se eu quiser ser promovido, mas inglês não faz o menor sentido para mim_. O que fazer, então? Não se pode apagar a necessidade. O inglês é a língua que mais se exige hoje em dia. O que é possível fazer para aprender uma língua se o único motivo que tenho para aprendê-la é a obrigação?

A motivação é importante, muito importante, mas não é porque começamos com uma motivação diferente da ideal que estamos fadados a não conseguir. _É possível aprender a querer_. Isso não se aplica apenas àqueles que aprendem uma língua por obrigação, mas também àqueles que aprendem uma língua por vontade própria. 

Como assim?

---

O processo é longo. Estamos falando de não menos do que seis meses, e provavelmente bem mais do que um ano. Bem mais. O tempo diminui de acordo com o seu empenho e com quanto a língua que você está aprendendo parece com as que você já fala. Naturalmente, vai ter dia em que não você não ter paciência. Vai ter dia em que você vai abrir o seu material de estudos e vai sentir asco. Então é preciso aprender a querer. É preciso traçar objetivos, debater consigo mesmo: o que eu posso fazer? O que posso ganhar? Como posso continuar? Qual é meu próximo objetivo nessa língua?

Traçar objetivos é importante. Talvez você queira aprender russo para ler Dostoiévski, mas Dostoiévski é difícil de ler até para os próprios russos. Tem que ter algo no caminho. Não ir direto no Dostoiévski. Não temos que esquecer o nosso grande objetivo, mas é bom traçar metas ao longo do trajeto. Se não sei falar nada de russo, talvez caiba eu primeiro aprender a letra de uma música? Ler um conto? Ler uma peça? Um livro com um vocabulário mais simples? Assistir uma série, um curta, um filme, jogar um jogo?

É importante encontrar formas de se divertir na língua. O processo pode ser incrivelmente divertido e, desde que você pelo menos goste da língua, ele tende a ser. Claro, ele não vai ser _sempre_ assim, mas é possível ajudá-lo a ser, com maior ou menor frequência. 

Considere também: o que é que você pode ganhar com ela, com essa língua? Pelo menos a respeito do inglês é possível falar o seguinte: não faltam utilidades, não faltam aplicações. Tomemos o inglês como exemplo: se você tem um objetivo, qualquer seja ele, é muito provável que saber inglês vai torná-lo mais fácil.

Falo do inglês pois é a língua que as pessoas mais querem aprender, não raro por necessidade. O útil pode ser unido ao agradável. Talvez você não tenha tanto interesse assim em literatura, mas você precisa aprender inglês de qualquer jeito. Porém, digamos que você tem interesse em engenharia. Ora, quantos artigos, vídeos, blogs ou livros a Internet não te dá acesso? Quantos desses não estão em inglês? Há informação que simplesmente não está disponível em outras línguas, ou está apenas mediante pagamento, ou mediante um pagamento mais caro, e assim por diante. Seja o que for a coisa que você tenha em mente, provavelmente saber inglês vai ter dar alguma vantagem nela.

Para outras línguas o seu interesse vai ter que ser mais pessoal. É necessário algum amor pela cultura, pela sonoridade, pela história, pelas peculiaridades do povo, pela etimologia. Por esse motivo, é bom que se busque compreender o que te atrai na língua, talvez até fazer uma lista e, se for possível, ir aumentando cada vez mais o tamanho dessa lista. Isso também se aplica para quem quer aprender inglês. Pode ser que você já saiba, mas acredite: é sempre bom lembrar.

A maioria das pessoas só busca aprender uma língua após estarem convencidas de que precisam aprendê-la, seja por necessidade ou interesse. Talvez você já esteja convencido; você já sabe que quer aprender. Ótimo, segure esse sentimento. Aproveite-o. Saiba, porém, que talvez um dia ele oscile, talvez um dia você desanime -- e eu não desejo nem espero que isso lhe aconteça, mas é provável sim que isso ocorra, e nesse caso lembre-se do que você leu aqui. Convença-se a continuar. Talvez seja necessário parar um dia, ou dois, ou duas semanas, mas, desde que você goste, mesmo que de saco cheio, volte. Apenas pare se não fizer mais nenhum sentido, se nem a beleza te segurar no seu objetivo -- pois a beleza também é um ótimo motivo.

## Resumo {-}

1. A motivação que temos para aprender uma língua muda a nossa relação com ela: se ela for boa e mais pessoal, tendemos a ter um processo mais agradável mais do que se aprendermos por obrigação ou para "mostrar pros outros".
2. Alcançar a fluência é perfeitamente possível, mas não é obrigatório. Se você quer aprender uma língua por um motivo que não exige de você a fluência, não tem porque obrigar-se a andar sete milhas quando uma só é necessária. Cuidado com o perfeccionismo. 
3. Ter uma boa relação com a língua que estamos aprendendo (e com a cultura e as possibilidades que estão associadas a ela) nos ajuda a manter a motivação, e pode tornar o processo divertido.
4. Disciplina é necessário. Mesmo que você goste muito da língua, vão haver dias em que você não vai aguentar mais. Prepare-se para isso, e não se apresse em interpretar essa exaustão como sinal de que "você não gosta da língua de verdade".
5. É importante não apenas considerar os motivos pelos quais você quer aprender essa língua, mas também procurar _outros motivos_ para manter o ânimo. Crie objetivos intermediários (de curto, médio e longo prazo) mais fáceis do que o seu objetivo final, para alcançar ao longo do caminho. Se o seu objetivo é ler um livro difícil no idioma original, considere realizar a leitura de múltiplos livros mais fáceis como etapas prévias -- por exemplo.
