
# A diferença entre aprendizado e aquisição {-}

É comum chamarmos a língua que queremos aprender de "L2", que significa "Língua 2" ou simplesmente "Segunda Língua". Daqui para frente chamarei a língua que queremos aprender de "L2", seja ela qual for. A  nossa primeira língua é chamada L1.

Entre os estudiosos do processo de aprendizado de L2, faz-se a distinção do que se chama de "aprendizado" e "aquisição". 

Veja bem, antes mesmo de ir para a escola para estudar a língua portuguesa você já a tinha adquirido (supondo que você é brasileiro e tem o português como língua nativa). Você já sabia falar, já sabia se comunicar, já sabia se expressar, perguntar, tirar dúvidas, reclamar, pedir. Se você ouvisse alguém dizer algo como "eu como isso todo dia", você seria capaz de entender que a palavra "como" nessa frase está relacionada com o verbo "comer", sem precisar saber o que diabos é um verbo pra entender isso. Você também sabe que a forma em que esse verbo está flexionado ("como", e não "comi"; "como, e não "comia") indica algo relacionado ao presente, e talvez também a hábitos. Existe algo de comum entre a palavra "como", "faço", "visto", "torço", "gosto", "odeio". Na escola a gente aprende que todas essas palavras estão na _primeira pessoa do singular do tempo presente do indicativo_.

Antes de ir para escola, então, você já tinha adquirido a compreensão de como se comunicar. Essa capacidade de falar e entender uma língua é o que os estudiosos do campo do aprendizado de línguas chama de "aquisição". Quando você aprende _sobre_ a língua, como o que é um verbo, sujeito, objeto, tempos presente, pretérito e futuro e outras coisas mais, você está fazendo o que se chama de "aprendizado".

A competência que vem com a Aquisição é algo intuitivo e estético. Quando você ouve (ou lê) algo que parece errado, você tem uma compreensão mais ou menos visceral de que algo está fora do comum. Se eu digo, "eu comerei isso ontem" ou "eu comia isso ano que vem", você consegue perceber que algo aí destoa da "forma correta" de se falar. Você sabe que esses verbos estão fora do contexto em que eles deveriam ser usados, mas você não precisa reconhecer a regra explícita para saber _por quê_. 

A Aquisição ocorre, largamente, de forma inconsciente. Ela é realizada por meio da imersão. Você não percebe que está adquirindo enquanto adquire. Você entende aqui e ali uma coisa, e sem perceber a sua capacidade de compreensão vai aumentando e você não sabe dizer exatamente em que ponto é que ele melhorou. Você sabe que melhorou, e sabe que foi fruto do tempo que você passou imergido na língua, mas não há tantos momentos isolados de _eureka_: há antes uma série de pequenas adivinhações corretas que você faz sem perceber e que vão se somando uma à outra. São pequenos grãozinhos que um a um vão entrando em um pote, e quando você menos percebe o pote está transbordando.

O Aprendizado, por sua vez, serve para explicar o que é Adquirido. Logo, se você quer falar, ler, ouvir uma segunda língua, os seus focos devem se voltar para Adquirir a língua, e não aprender sobre ela. Com o passar do tempo, depois de muito tê-la adquirido, você poderá até mesmo _inferir_ as regras: sabendo que "é assim que as pessoas falam", você conseguirá explicar as regras gramaticais sem precisar recorrer a um livro. Poderá, talvez, pegar um livro de gramática e ver ali uma série de regras que você já sabia, mas que "não sabia que sabia".

Pouco te servirá, então, saber que o verbo "is" não deve ser usado com "you" porque este serve para a segunda pessoa (do singular ou do plural) enquanto o "is" serve para a terceira pessoa do singular. Você não aprende isso para entender ou para falar, mas você _percebe isso_ depois de muito ter entendido e de muito ter ouvido falar. Se você se preocupar com isso antes da hora, o resultado é que você ficará calculando, e sua fala pagará pedágios.

Gramática, entretanto, não é inútil. [Ela tem seu lugar][O papel da gramática], mas é diferente do normalmente considerado em muitos materiais didáticos tradicionais.

O necessário é desenvolver intuição, instinto, senso estético. Você tem que ser capaz de ver a frase "_you's an strange dog_" e saber que ela está errada porque ela é feia e fora do comum e dos hábitos dos falantes da língua -- dos músicos populares aos poetas clássicos --, tal como você julgaria como feia a frase "o chuveiros quebrado tá". Tem algo de errado com essa frase e você sente isso no estômago. Qualquer regra que explique porque está errado é secundária para os nossos propósitos.

Como então podemos desenvolver essa sensibilidade? Veremos na próxima página.

## Resumo {-}

1. A língua que nós queremos aprender é normalmente chamada de L2 pelos estudiosos de aprendizado de idiomas. A nossa língua materna é chamada L1.
2. Duas palavras-chave são importantes no estudo de línguas: "Aprendizado" e "Aquisição".
3. "Aprendizado" é o estudo _sobre_ a língua. Sob a alcunha de "Aprendizado" caem os esforços para entender descrições _a respeito da língua_. O estudo da gramática é um tipo de aprendizado.
4. "Aquisição" é a compreensão intuitiva que nós obtemos de uma língua por meio da nossa exposição.
5. Tornar-se fluente e confiante em uma língua é resultado de um longo processo de Aquisição que se dá por meio da imersão.
6. O estudo da gramática tem o seu lugar, mas ele não confere a confiança e a fluência normalmente desejados. Excesso de consciência sobre gramática no momento da fala resulta em um discurso travado, em que o falante precisa parar com frequência para "calcular" como estruturar as frases de acordo com normas gramaticais. Esse processo pode ser automatizado pelas práticas de Aquisição.
