# Melhores conteúdos para aprender uma língua  {-}

Hoje em dia é possível praticar a imersão por meio da Internet. O consumo de conteúdo audiovisual é por si só capaz de fomentar a nossa compreensão. As cenas nos ajudam a entender o significado das palavras por contexto. 

Entretanto, isso às vezes pode não ser engajante, em virtude da dificuldade que vem com não entender aquilo que estamos assistindo. Nós precisamos estar interessados, e pode ser frustrante gastar de trinta minutos a algumas horas por dia assistindo coisas das quais entendemos muito pouco. Por esse motivo eu acho que jogos digitais são as melhores mídias educativas em idiomas: eles têm a capacidade de serem divertidos mesmo se não entendemos o que os personagens estão falando. Séries e filmes não costumam ter essa característica. Livros, então, nem se fala.

No início a imersão pode ser frustrante, pois estamos entendendo muito pouco. Nós não gostamos de passar horas sem entender nada. Porém, isso passa: depois das primeiras tantas horas, você se acostuma a não entender mais, e aí acontece uma coisa muito interessante: _você relaxa_. Sentir-se relaxado nesse processo é muito importante. Você estará aprendendo sem nem perceber. O pré-requisito é simples: que você preste atenção. Tente entender quais são as intenções dos personagens em cena. O que eles querem? O que eles estão fazendo? Não se preocupe em atender toda e cada palavra; basta entender a mensagem e o contexto. 

A princípio, vai tudo parecer um monte de ruído e sons sem sentido. Aqui e ali, umas palavras vão se repetir e você vai começar a perceber padrões. Aqui e ali, você vai _reparar_ em uma palavra, que você ainda não entende, mas que você já aprender a reconhecer. Se isso aconteceu, é questão de tempo até que você entenda o que ela quer dizer.

Faça o experimento: escolha algum filme, série ou jogo no idioma que você quer aprender, mas cujas falas você entende pouco. Assista um ou dois episódios, ou assista o filme inteiro, ou uma ou duas horinhas do jogo, e deixe-o de lado. Agora vá e passe algumas horas se expondo a _outro_ conteúdo nessa mesma língua: jogue outro jogo (até o final) na sua L2; assista vários filmes ou uma série inteira. Depois disso, volte para aquele primeiro filme, série ou jogo que você deixou de lado. Será surpreendente: você vai se perceber entendendo _muito_ mais. O surpreendente? Você aprendeu, mas _não percebeu_ que estava aprendendo.

Tudo isso supõe que você vai fazer isso com o áudio **e a legenda** na língua escolhida. Lembre-se: **não tire legendas nem as traduza, nem use dublagens.** 

Também cabe dizer que se a língua que você quer aprender usa outro sistema de escrita, é necessário que você o aprenda. Aprender sistemas de escrita pode parecer assustador, mas acredite: é uma das partes mais fáceis de uma língua. As exceções a essa regra são as línguas que utilizam ideogramas (tais como japonês e mandarim), mas mesmo sistemas de escrita muito diferentes do nosso (como árabe, hebraico e russo) são relativamente fáceis de compreender. Na página sobre [sistemas de escrita][Sistemas de escrita] eu dou um exemplo do que esperar ao aprender algo como um novo alfabeto.

## I+1 {-}

Mas e se eu não gosto ou não tenho acesso a conteúdo audiovisual? Nesse caso, restam-me duas opções: contratar um tutor ou fazer uso de leitura e de podcasts.^[Claro, existem os livros didáticos. São ferramentas úteis, ainda que engessadas, para nos ajudar a aquirir línguas. Aqui, entretanto, estamos falando de _imersão_, então não vamos abordar esse tipo de material.] Mas quanto a esses dois últimos, simplesmente não dá pra entender nada se eu já não sei alguma coisa, certo? Em parte, sim. Para isso é importante usarmos [sistemas auxiliares][Ferramentas auxiliares no aprendizado de línguas].

Mas mesmo para quem não gosta de conteúdo audiovisual, pode ser chato _limitar-se_ a esse tipo de coisa. Você pode querer ler ou ouvir podcasts. Seja por não gostar de filmes, séries e jogos, seja por querer variar um pouco, quando não nos apoiamos na visão para auxiliar o nosso aprendizado nós precisamos criar _uma progressão_. Temos que partir de um conteúdo relativamente fácil e confortável para conteúdos gradativamente mais complexos e desafiadores.

Convido você, portanto, a conhecer o conceito de "$I+1$", que é comum no estudos sobre aquisição de línguas. Considere o seu atual domínio na sua L2. Vamos dizer que o seu nível nela é representado pela letra $I$.

Se $I$ é o seu nível, então $I+1$ significa "o seu nível atual" mais "um pequeno incremento". Você fala bem o português brasileiro. Digamos que você pegue para ler um texto do Machado de Assis. Vou usar como exemplo um breve parágrafo de Memórias Póstumas de Brás Cubas:

>Bom e fiel amigo! Não, não me arrependo das vinte **apólices** que lhe deixei. E foi assim que cheguei à cláusula dos meus dias; foi assim que me encaminhei para o _undiscovered country_ de Hamlet, sem as ânsias nem as dúvidas do moço príncipe, mas pausado e **trôpego** como quem se retira tarde do espetáculo. Tarde e aborrecido. Viram-me ir umas nove ou dez pessoas, entre elas três senhoras, minha irmã Sabina, casada com o Cotrim, a filha, — um lírio do vale, — e... Tenham paciência! Daqui a pouco lhes direi quem era a terceira senhora. Contentem-se de saber que essa anônima, ainda que não parenta, padeceu mais do que as parentas. É verdade, padeceu mais. Não digo que se **carpisse**, não digo que se deixasse rolar pelo chão, convulsa. Nem o meu óbito era coisa altamente dramática... Um solteirão que expira aos sessenta e quatro anos, não parece que reúna em si todos os elementos de uma tragédia. E dado que sim, o que menos convinha a essa anônima era aparentá-lo. De pé, à cabeceira da cama, com os olhos estúpidos, a boca entreaberta, a triste senhora mal podia crer na minha extinção.

Em negrito acima estão três palavras que não são tão frequentemente utilizadas. Vamos imaginar uma pessoa hipotética, que não conhece essas três palavras. Ela conhece todas as outras, menos essas três. Ora, ela provavelmente será capaz de entender perfeitamente, ou quase perfeitamente, o que o autor quer passar neste trecho. Neste caso, o vocabulário desse parágrafo está apenas _um pouquinho_ acima do nível comum de domínio da língua portuguesa dela. 

Esse é o ponto ideal para o nosso material de leitura, para nossos podcasts. Para ser sincero, até mesmo para conteúdo áudiovisual esse nível é _ideal_. Porém, com conteúdo audiovisual nós podemos ser um pouco mais flexíveis; quando trabalhamos apenas com texto ou apenas com áudio já fica mais difícil destoarmos disso.

Dito isso, e se eu não encontrar algo que esteja tão pouco acima do meu nível? O mais importante -- lembre-se -- é que você mantenha _interesse_ no conteúdo. Encontrar conteúdo que se adeque perfeitamente ao seu $I+1$ pode ser difícil, então é bom procurar por esse tipo de coisa, mas não se desanimar se você não conseguir encontrar. Se você consegue continuar interessado em um filme que não é o seu $I+1$, mas o seu $I+10$, ótimo! Algumas pessoas se focam excessivamente em se ater ao $I+1$, e se torturam por horas assistindo Masha e o Urso, Teletubbies e Peppa Pig. Essas coisas são fáceis de compreender, mas obrigar-se a assistir isso pode ser uma tortura.

O mais provável é que você tenha que fazer alguma concessão, principalmente se você quiser trabalhar com a leitura: ora consumir conteúdo mais interessante, mas menos compreensível, ora consumir conteúdo mais compreensível, mas menos interessante. Com o tempo você vai ter acesso a cada vez mais e mais coisas e poderá dar cada vez mais vazão ao seu interesse.

Diga-se de passagem, se o $I+1$ é desejável e o $I+10$ é aceitável, entenda-se que o ideal é seguir sempre incrementando. Não fique parado confortavelmente lendo e relendo, assistindo e reassistindo, material do qual você já entende absolutamente tudo. 

A seguir vou falar um pouco mais sobre _os tipos de conteúdo_. Apesar de dividi-los em categorias, você não deve "escolher uma". Utiliza quantos destes meios a sua energia o seu interesse permitirem.

## Tipos de conteúdo  {-}

### Jogos {-}

Conteúdo audiovisual -- séries, filmes e jogos digitais -- tem um certo privilégio. Ele apresenta as palavras em _cenas_, e as _cenas_ nos ajudam a entender o que essas palavras significam. Eu acredito pessoalmente que os jogos digitais são os mais úteis meios de adquirir uma língua, já que eles exigem mais da sua atenção do que séries e filmes, e conseguem ser divertidos e engajantes mesmo a mercê da compreensão. 

**Mas atenção**: nem todos os jogos têm o mesmo valor. De nada serve que você fique horas jogando FIFA com um amigo no seu PlayStation, já que nesse jogo tem pouco ou nenhum diálogo na sua L2. O mesmo se aplica a jogar jogos online em que não há interação entre jogadores, ou se os jogadores, em sua maioria, falam a mesma língua que você. O interessante são jogos _single-player_ (para apenas um jogador) e ricos em enredo, em história, _ou_ jogos online em que há muita interação entre os jogadores _e_ eles falam a sua L2. Ou seja, nada de passar horas jogando Minecraft.

É interessante que os jogos tenham dublagem na sua L2 para que eles sejam mais proveitosos. Jogos legendados mas não dublados podem ser úteis, mas são menos preferíveis.

Não pule os diálogos e os trechos cinematográficos ("_cutscenes_").

### Filmes, séries, documentários, noticiários etc. {-}

O procedimento para aproveitar estes não difere muito de como se faria com jogos: apenas escolha algo do seu interesse e coloque a dublagem e a legenda na sua L2; preste atenção -- nada de ficar no celular fazendo outra coisa durante a imersão; não se preocupe em ficar voltando para entender tudo completamente e traduzir toda e qualquer passagem. Cabe, com certeza, pausar e rebobinar e tentar dar mais atenção àquelas cenas que parecem ser mais intensas e importantes para o desenvolvimento da trama. 

_Rebobinar não é proibido_, só não é _necessário_. Entender tudo _não é obrigatório_, mas empenhar-se para fazer isso também é válido. É questão de equilíbrio: se você tentar ser muito minucioso e entender tudo a cada vez que a legenda muda, sobretudo se você não domina bem a língua ainda, você vai ficar estressado; a imersão se tornaria muito cansativa. Relaxe e curta o programa. Volte pra tentar entender melhor só quando você quiser. 

Assista e confie. Mesmo não entendendo tudo, você estará aprendendo. Lembre-se do experimento proposto no início desta página.

#### Séries {-}

Não é possível ignorar o potencial que as séries fornecem aos espectadores. _Sitcoms_ como Friends, Two and a Half Man e The Big Bang Theory possuem enorme valor. Esse tipo de material é especialmente útil pois ele trata do cotidiano. Nele você pode ver ser utilizado um linguajar mais comum e informal. A língua utilizada costuma ser mais flexível também. Em livros didáticos, em comparação, é comum que os diálogos e exercícios sejam engessados e utilizem uma língua artificial e exageradamente controlada. 

Elas também costumam ter uma infinidade de temporadas, o que resulta em mais conteúdo. 

Claro, se você não gosta de _sitcoms_ ou séries de comédia, sinta-se à vontade e assista as do tipo que você gosta. 

Séries também têm maior duração do que filmes, e portanto elas nos concedem um maior volume de conteúdo. Elas costumam, também, a girar mais ou menos em torno de um mesmo tema, então o vocabulário de cada série vai variar menos _dentro da série_ do que _entre séries_, o que pode nos ajudar na compreensão. Se você estiver vendo uma série sobre militares, naturalmente vão ser usadas mais palavras relacionadas a armas e hierarquias do que em uma série sobre um restaurante.

#### Filmes e documentários {-}

Filmes não ficam atrás: basta que você encontre um tema que você goste e procurar os filmes. Dependendo da língua que você está estudando, pode ser mais fácil encontrar filmes do que série. Os serviços de _streaming_ como a Netflix e a HBO, ou plataformas como CrunchyRoll, são de extrema valia. Não é tão fácil encontrar conteúdo pra todas as línguas nos serviços de _streaming_, e nem todo streaming tem um leque de línguas distribuído de forma igualitária. Pode ser mais fácil encontrar conteúdo em russo no Mubi e no YouTube do que na Netflix, por exemplo. O inglês, entretanto, está por toda parte, e é fácil encontrar todo tipo de material nessa língua. 

O mesmo se aplica a documentários.

#### Noticiários {-}

Noticiários costumam ser mais difíceis, pois costumam fazer uso de vocabulário técnico -- tratando de coisas como economia, política, acidentes, utilizando vocabulário jurídico, científico, etc. Se isso for do seu interesse e necessidade, então haverá utilidade, mas em geral o vocabulário em noticiários costuma ser mais rebuscado e formal.

### Livros e podcasts {-}

É necessário ter algum grau de compreensão do vocabulário nesse tipo de material .Esse tipo de prática frequentemente precisa ser apoiada por alguma [ferramenta auxiliar][Sistemas de repetição espaçada]. Isso é especialmente verdade caso você esteja aprendendo uma língua muito diferente da nossa (como o alemão), mas se você estiver aprendendo algo como o espanhol é possível ler artigos e livros inteiros com um grau tolerável de dificuldade e incompreensão.

Existem, entretanto, livros e podcasts nivelados, cujo intuito é justamente oferecer conteúdo I+1 para leitores e ouvintes em diferentes níveis de compreensão na língua. Estes são "didáticos", mas não no modelo convencional. Em vez disso, eles têm o objetivo de servirem _como_ imersão. Vamos tratar destes agora. 

#### Livros {-}

Existem sites como o [lingua.com](https://www.lingua.com/) que disponibilizam conteúdos por escrito, separados por níveis ("leitura nivelada") que estão de acordo com a categorização do Quadro Europeu Comum de Referências para Línguas (CEFR). Pode-se compreender esta classificação da seguinte forma:

- A1 - iniciante absoluto
- A2 - iniciante  
- B1 - intermediário 
- B2 - alto intermediário 
- C1 - avançado 
- C2 - proficiente 

Para a língua inglesa, o melhor site que conheço é o [English e-Reader](https://english-e-reader.net/findbook/), que fornece uma gradação ainda maior de textos (tendo oito classificações -- em comparação com as seis da CEFR --, de "starter" a "unabridged"), e apresenta versões adaptadas de textos originais.

Após passar um tempo lendo textos nivelados, você provavelmente vai querer testar seu progresso em textos originais, isto é, feitos não com fins didáticos, mas para nativos no idioma. Para este fim, acredito que os conteúdos mais convenientes para imersão são contos ("_short stories_") e peças teatrais. 

Ler um romance inteiro pode ser muito pesado para um iniciante ou para alguém que ainda não se sente tão confortável com a língua. Assim, contos se mostram muito convenientes para aqueles que abordam a literatura com fins de aprendizado. Estes textos podem ter trechos difíceis e até mesmo incompreensíveis, mas como eles são curtos tais dificuldades se tornam mais toleráveis.

Da mesma forma, peças teatrais costumam ser repletas de conversas, o que deixa de fora as complicadas descrições de cenários e os longos e complexos devaneios. Claro, existem trabalhos teatrais mais complicados, como os de Shakespeare, e estes convém deixar para quando nos sentirmos mais confortáveis com a língua em questão. Por outro lado, há peças riquíssimas e muito interessantes que não fazem uso de um vocabulário tão rebuscado, como as de George Bernard Shaw.

Ao ler, não o faça de forma obsessiva. Com isso quero dizer que você não deve de antemão tentar decifrar o significado de cada palavra. Leia o parágrafo inteiro de uma vez, talvez mais do que um parágrafo -- talvez a história toda -- e depois volte para analisar as partes que permanecerem incompreendidas. Não é necessário entender tudo de primeria. Às vezes o que acontece no final de uma frase nos ajuda a compreender o que está no início dela, e portanto "travar" em uma palavra é com frequência uma perda de tempo. Leia a largas pinceladas, e depois volte e releia com maior detalhe. E releia.

E releia.

##### Características especiais da leitura {-}

Mas apesar de a leitura pode ser mais difícil de adentrar do que o conteúdo audiovisual, ela possui certas potencialidades que não são comuns às outras mídias.

O motivo que torna a leitura mais difícil para iniciantes (principalmente se não utilizamos material nivelado) é também o motivo que a torna o melhor método para enriquecermos nosso vocabulário: nela encontramos palavras que não encontramos normalmente na língua falada.

Todos nós conhecemos um número maior de palavra do que utilizamos. Esse é o chamado _vocabulário passivo_, enquanto as palavras que habitualmente empregamos constitui o nosso _vocabulário ativo_. Este último só pode crescer em função do primeiro: quanto maior o nosso vocabulário passivo, maior em potencial se torna o nosso vocabulário ativo, e com ele a nossa capacidade de precisão; e quanto maior nosso vocabulário passivo, maior nossa compreensão.

Ao ler uma história, você entrará em contato com termos pouco utilizados em conversas cotidianas: "abobadado", "pé-direito", "conspícuo", "sanguíneo", "marmóreo" etc. Durante descrições de cenários, de pessoas, situações, pensamentos privados e outras coisas, é comum deparar-se com um volume maior de palavras "raras". 

Tais palavras, quando compreendidas, não necessariamente adentrarão o nosso vocabulário ativo, mas farão parte do pano de fundo com o qual compreenderemos o que dizem _os outros_. Quando você sabe o que é uma "abóbada", pode se comunicar com maior facilidade, sem precisar apelar para termos como "teto arredondado", "telhado recurvo", "teto em forma do lado de dentro de uma cebola oca" ou coisa do gênero; "inconspícuo" não é a mesma coisa que "escondido" ou "imperceptível", e pode servir melhor em um contexto do que "difícil de perceber".

Além disos, as palavras muitas vezes compartilham uma estrutura, seja ela implícita ou explícita. Ao conhecer um grande número de palavras, é possível compreendermos um maior número de palavras mais ou menos comuns que são a elas relacionadas. As palavras compartilham radicais, prefixos e sufixos, e a compreensão das partes das palavras pode nos auxiliar na compreensão de outras que têm partes em comum. "Roughly", "Coldly", "Possibly" e "Slowly" têm todas o mesmo final, "-ly", e portanto têm _algo em comum_. "Possible", "impossible", "possibility" e "possibly" têm todas o mesmo radical, mas finais diferente. Se você entende as partes diferentes da palavra, fica mais fácil compreender outras palavras que são compostas por essas partes.

Em um caso extremo, "awesome" é composto de "awe" e o sufixo "-some". "Quarrel" é briga, e "quarrelsome" é briguento; "worry" é "preocupação" e "worrisome" é "preocupante". "-some" tem algo a ver com "cheio de" ou "causador de". Algo "worrisome" é algo que te causa "worry". Logo, algo "awesome" é algo que te causa "awe". Mas o que é "awe"? "Awesome" costuma significar algo "positivamente incrível", mas "awe" é uma emoção que remete simultaneamente a espanto, pavor, admiração e reverência, como o castelo de um tirano ou um monstro gigante. Assim, em certos casos específicos, "awesome" pode ser utilizado para uma situação amedrontadora, e não apenas positiva. Esse tipo de nuance você só capta _ampliando_ o seu vocabulário e conhecendo as partes das palavras.

Esse tipo de uso, seja da palavra, seja de parte dela, não é comum na língua falada, e pode mais facilmente (às vezes unicamente) ser acessado pela via da leitura. E por que diabos alguém pode querer saber dessas coisas? Simples: para ter flexibilidade, alcance e precisão. O que a língua não alcança é difícil de descrever, é difícil de entender, e é difícil de compartilhar.

Pode então ser mais confortável utilizar apenas métodos audiovisuais para aprender, principalmente no início, mas o alcance que eles nos conferem não é equiparável ao da leitura, principalmente nos níveis mais avançados. Assim, não tome a leitura como uma obrigação, principalmente no início, mas saiba que existe um certo grau de domínio sobre a língua que só pode ser acessado por meio dela.

#### Podcasts {-}

Quanto aos podcasts, existem também produções voltadas justamente para estudantes da língua -- são os podcasts nivelados. Eu não conheço nenhum tão bom para o inglês ou qualquer outra língua quanto o do [https://www.youtube.com/@RussianWithMax][Russian with Max] é útil para o russo: ele realmente preenche todos os requisitos e é o que mais se aproxima do ideal. Você o verá falando de múltiplos assuntos, em um russo lento e simples, e ocasionalmente, quando necessário e em conformidade com o assunto, ele apresentará uma palavra nova e a explicará _em russo_, utilizando palavras comuns.

Você pode pesquisar por podcasts do seu interesse no YouTube e em plataformas de _streaming_ como o Spotify. Dito isso, muitos podcasts caem no vício de _não falarem na língua_, mas sim de _falarem sobre a língua._ O YouTube está repleto de podcasts que reproduzem este erro, e eles são incrivelmente numerosos no caso da língua inglesa. Tais podcasts vão criar múltiplos vídeos e capítulos falando de detalhes gramaticais, sobre como usar esta ou aquela partícula, ou irritantemente ensinando "listas de palavras", e vão dedicar pouquíssimo tempo a de fato apresentar conversas, histórias ou tópicos no idioma em questão.

O que você quer, então, é simples: podcasts que falam na língua que você quer aprender; que falam devagar; que falam sobre múltiplos tópicos ou sobre tópicos do seu interesse; e que, ao apresentar uma palavra nova, expliquem-na sem sair da língua em questão. Pode ser difícil encontrar um podcast com _todas_ essas qualidades, então se preocupe se você não encontrar um tão próximo do ideal.

E claro, é perfeitamente válido utilizar podcasts normais, não-didáticos. Se mesmo com um grau de compreensão reduzida você conseguir manter o interesse neles, divirta-se.

## Necessidade de ferramentas de apoio para a imersão {-}

No caso do inglês e de quaisquer outras mais diferentes da língua portuguesa que o Espanhol, inevitavelmente será necessário suplementar com algum tipo de ferramenta auxiliar. Todos podem se beneficiar destas ferramentas -- e, estrategicamente falando, é melhor utilizá-las do que deixar de fazê-lo, por qualquer que seja o motivo.

O benefício que elas trazem é justamente tornar o processo de aprendizado _mais rápido_. Elas podem ser imprescindíveis no caso da leitura e do uso de podcasts, mas o fato de ser possível contorná-las por meio do consumo de mídia audiovisual não faz com que seja bom fazê-lo.

Elas são os chamados "sistemas de repetição espaçada". Irei apresentá-las e demonstrar como utilizá-las nos capítulos seguintes. 

## Resumo {-}

1. O início do processo de imersão é frustrante e causa ansiedade. Entretanto, aguente firme: fique algumas horas, acostume-se a não entender. Logo você se sentirá mais relaxado. Aí, apenas aproveite.
2. Preste atenção. Não adianta "fingir" imersão, dando _play_ num filme e ficar usando o celular em vez de assisti-lo.
3. Não se preocupe em entender tudo; não se preocupe em ficar voltando para decifrar cada linha da legenda. Dito isso, nada disso é proibido: quando você quiser, volte um pouco atrás.
4. O conteúdo ideal é representado pelo conceito de $I+1$, ou seja, um conteúdo _apenas um pouco_ acima do seu nível atual na sua L2.
5. Pode ser difícil encontrar um conteúdo que se adeque perfeitamente ao seu $I+1$. Você pode ter que realizar um certo compromisso, ora consumindo material mais fácil mas menos interessante, ora assumindo material mais interessante mas mais difícil.
6. Jogos digitais voltados para a narrativa são o melhor tipo de conteúdo -- se você gosta deles -- pois possibilitam que você se divirta mesmo que você não esteja entendendo o que está acontecendo.
7. Séries e filmes, além de serem ótimas para o aprendizado devido ao fato as cenas nos ajudarem entender as palavras pelo contexto visual, também podem nos apresentar um vocabulário mais "natural" e flexível do que os que encontramos em materiais didáticos convencionais.
8. Livros e podcasts normalmente são mais difíceis, mas há livros e podcasts "nivelados", feitos para servir como material de imersão para estudantes da língua.
9. Embora o material mais proveitoso para te ajudar a adquirir a língua seja o material audiovisual, há um certo nível de proficiência que só pode ser alcançado por meio dos livros. O domínio do vocabulário que a leitura pode te propiciar não é comparável ao que pode ser aprendido por meio de séries. Assim, mesmo que você considere deixar os livros pra depois, saiba que "os níveis mais avançados" só são alcançáveis por meio deles.
