# A interação entre repetição espaçada e imersão {-}

No processo de imersão, há tanta coisa que não compreendemos que não é possível que de antemão percebamos tudo. Acabamos então percebendo apenas o que vemos com maior frequência. Ao ver uma palavra pela primeira vez, mal se a percebe. Ela é um ruído incompreensível no meio de muitos outros, mas logo, no meio do ruído, você vê de novo aquela palavra, e aos poucos ela se torna familiar. E de novo. E de novo. Pronto. Você percebeu uma palavra, uma expressão, um sufixo, algo do gênero. Por conta disso, você será capaz de inferir melhor o seu significado pela forma como ela é usada. 

É frequente que simplesmente continuar vendo essa palavra em novos contextos nos leve à compreensão do que ela significa e em quais situações devemos utilizá-la. Assim, a imersão nos leva à percepção, e a percepção nos leva, com ajuda da atenção e da instiência, à compreensão.

Entretanto, esse processo pode ser acelerado pelo uso de sistemas de repetição espaçada, tais como o que aprendemos nas páginas anteriores. Se eu vejo uma palavra repetidas vezes durante minha imersão mas não a compreendo, assim que eu a ver no meu sistema de repetição espaçada, por eu já ter a memória dela ocorrendo em outros momentos, eu certamente a fixarei com maior facilidade. Se eu vejo ela "lá fora", na imersão, retenho-a com muito mais facilidade "aqui dentro", no meu esforço de memorização.

Da mesma forma, quando vejo algo no meu sistema de repetição espaçada, se a palavra que está lá não for muito familiar, não fizer conexão com muitas ideias, nós provavelmente não vamos retê-la com facilidade. Essa tenderá a ser uma palavra "teimosa", de difícil memorização, justamente por não ter algo a que se conectar. A imersão, então, dá material a que ela pode se conectar: quando a vemos acontecendo em um ambiente não-controlado, "na natureza", por assim dizer, nós traçamos uma conexão entre aquilo que aprendemos por repetição espaçada e o que vimos durante a imersão.

Podemos ver então: a imersão fortalece o uso do sistema de repetição espaçada e a repetição espaçada reforça a imersão. ^[Você pode inferir disso que pode haver uma relação semelhante entre a imersão e a gramática. Sobre isso eu delineio em maior profundidade na página sobre [o papel da gramática][O papel da gramática]: nesta aqui nós trabalharemos exclusivamente a respeito do lugar da repetição espaçada.] Pode entretanto haver uma certa tentação em negligenciar um dos dois: ora praticar só a imersão, ora só fazer exercícios de memorização com repetição espaçada. Dessas duas atitudes, a segunda é a mais nociva. 

- **O que acontece se eu _apenas_ praticar a imersão?**

Você pode muito bem aprender uma língua do básico ao avançado só com imersão. É simples: abre o seu jogo, a sua série, o seu filme, coloca **tudo** no idioma desejado e vá em frente. O problema é que esse procedimento será mais demorado e potencialmente frustrante. O papel da repetição espaçada é portanto o de acelerar os ganhos que obtemos com a imersão.

- **E se eu _apenas_ usar sistemas de repetição espaçada?**

Por outro lado, se você tentar apenas memorizar listas e listas de palavras sem nunca vê-las sendo usadas por nativos da forma como elas devem ser usadas, você está perdendo o seu tempo. Para aprender a língua você precisa passar tempo com a língua, e não apenas com uma parte dela. Aprender o dicionário inteiro de antemão pode sim te ajudar a ter uma imersão mais produtiva, mas _inclusive aprender o dicionário inteiro_ vai ser mais fácil com ajuda da imersão, por conta do que foi mencionado acima sobre conexão. 

E se você tentar aprender milhares de palavras antes de mergulhar de cabeça na língua que você quer de fato aprender, quando você de fato mergulhar você vai perceber que você não sabe falar a língua. O que vai acontecer é o seguinte:

1. Você pode tentar simplesmente "traduzir" da sua língua nativa para a sua língua-alvo. 

O problema de fazer isso é que as línguas não correspondem entre si de forma matemática, então mesmo que você consiga fazer a tradução, será uma tradução literal e descolada da cultura que vem associada à língua. Lembre-se: língua vem sempre associada com cultura, e no meio dessa cultura não estão incluídos apenas vestimentas e estilos musicais peculiares, mas hábitos linguísticos que podem soar estranhos quando traduzidos literalmente. Por exemplo, se quisermos dizer algo como "vambora!" em inglês nós diríamos "let's go", que significa literalmente "deixe-nos ir". Em russo é ainda pior: "vambora!" seria "давай" (pronuncia-se "davái"), que signica "dê", do verbo "dar". Se você simplesmente traduzisse "vamos embora" para a sua língua alvo seria bem provável que você fosse mal-compreendido. Para não cometer gafes desse tipo o procedimento é simples: conhecer de antemão como os nativos falam essas coisas. E como se faz isso? Você adivinhou: imersão.

2. Você pode passar pelo peculiar caso de "conhecer todas as palavras mas não entender nada da frase". 

Isso acontece muito entre os estudantes de japonês, mas não é particular a eles. O motivo disso está associado ao anterior: língua vem com cultura, e a cultura contém em si hábitos linguísticos peculiares. Pode ser que você conheça todas as palavras, mas não saiba que uma delas tenha um outro significado menos usual do que aquele que você conhece. Pode ser também que as palavras isoladas signifiquem uma coisa, mas quando você as junta numa sequência elas signifiquem algo bem diferente. Um exemplo tosco: o significado de "not", "with" e "standing" pode ser bem simples, mas a palavra "notwithstanding" tem um significado muito diferente de cada uma delas. Esse é um exemplo de aglutinação em que múltiplas palavras viram uma só, mas há casos em que mesmo separadas as palavras podem ter significados muito diferentes. Isso pode parecer um tanto assustador, mas o remédio é simples: imersão.

Apenas aprender as palavras não basta: é necessário aprender com elas interagem.
