# Ansiedade de exposição {-}

Nesta página vamos abordar uma série de equívocos que os aprendizes de línguas com frequência cometem. Duas são as grandes razões por trás desses equivocos: ansiedade e perfeccionismo. Pode-se dizer que perfeccionismo é só mais uma espécie de medo ou de ansiedade. Dizer-se perfeccionista de modo a implicar que isso é um defeito pode ser uma forma velada de se gabar -- "até os meus defeitos são produtivos" --, mas aqui nós veremos como essa atitude não tem nada de positiva. 

## O medo de se expor

Todos os problemas que vão ser expostos nessa página de alguma forma se relacionam a este aqui. A verdade é que **expor-se a material nativo na sua língua-alvo nos faz sentir ansiedade**. Principalmente se nós formos adultos, é difícil não sentir _cobrança_ diante de qualquer coisa que estamos fazendo. Nós queremos fazer as coisas direito. Assim, quando algo nos parece tão incompreensível quanto uma língua estrangeira nós podemos adotar o impulso de deixar pra depois, e o resultado é tentar nos preparar mais antes de voltar. Isso pode gerar um ciclo vicioso, em que nós nunca de fato saltamos para a imersão. Prepar-se eternamente, aprender todas as regras gramaticais, é como ler um manual de andar de bicicleta. Ajuda, mas você tem ter a experiência direta.

A verdade é que, sim, é ansiogênico. Sim, nós vamos entender muito pouco e, no início, quase nada. Mas isso é parte do processo.

## O medo de não entender

Ergo, está associado ao medo de se expor o medo não entender. Se não entendo, é errado, é inútil; não deveria perder o meu tempo com uma língua que eu não entendo.

Expor-se e não entender nos causa uma reação visceral, uma ansiedade, um desejo de sair dali. Parece perda de tempo. É difícil confiar no processo quando estamos entendendo tão pouco. Podem vir mil e um sentimentos, síndrome do impostor sendo uma delas, mas também pode vir a tentação de "procurar algo mais eficiente".

Qual é o problema? O problema é que a língua estrangeira no início realmente soa como um monte de ruído. Com o tempo, entretanto, esse ruído se organiza em padrões dentro das nossas cabeças. O que antes era só um amontado de palavras indecifráveis não apenas quanto ao seu significado mas também quanto ao seu tipo (se é verbo, se é adjetivo etc.) passa ter arestas mais definidas.

**A imersão causa ansiedade**. Como vencer essa ansiedade? **Sujeitando-se a ela**. O curioso é que se você conseguir ficar algumas horas se expondo à sua língua alvo, mesmo sem entender, uma hora você _se acostuma a não entender_. Isso é **bom**. Verdadeiramente bom. No início pode ser doloroso praticar a imersão, mas com a insistência nós nos acostumamos a não entender, e é isso que queremos. Se nós nos acostumarmos a não entender, nós vamos relaxar. Se nós relaxarmos, aí passamos a aprender mais. E é aí que a mágica acontece: prestando atenção enquanto relaxado, sem perceber você está aprendendo.

## O medo de falar errado

O desejo de aprender uma língua comumente está associado ao desejo de _falar_ na língua. Não raro é algo vaidoso, um desejo de mostrar para outros que nós sabemos falar um outro idioma. Outras vezes é uma necessidade: meu trabalho exige isso de mim, ou eu poderei obter uma função melhor, e portanto uma promoção, no meu trabalho se eu conseguir falar tal língua. Talvez eu consiga um emprego em uma empresa de outro país, e assim poderei ganhar em dólar ou euro enquanto gasto em reais.

"Falar" é uma dessas coisas que nós queremos fazer com perfeição. Não achamos tolerável cometer erros de fala. Como podemos, então, falar sem errar? _Sabendo como as pessoas falam_. Isso a gente só adquire de fato pela compreensão, e a compreensão só se obtém com a imersão. Quanto mais e melhor entendermos, melhor falaremos.

Mas como superar o medo de falar? E melhor, como falar da forma correta?

### Interlúdio: o desejo de falar perfeitamente

É necessário de antemão que você esteja aberto à possibilidade de cometer erros na fala. Saiba que grandes empresários, intelectuais, comerciantes, CEOs, professores, autores etc. se comunicam rotineiramente em línguas estrangeiras sem dominá-las totalmente. Essas pessoas são capazes de falar bem o suficiente; elas têm um vocabulário amplo, mas cometem um ou outro erro gramatical quando falam. **É possível sim** falar sem erros, mas como **a língua é algo que se habita**, isso só vem com um longo período de habitação na língua. Falo para lá de cinco anos. Provavelmente dez ou mais. E se a língua estiver intimamente conectada ao seu estilo de vida, profissão, hobbies, moradia, isso é perfeitamente factível.

Mas isso pode parecer um pouco desanimador. Queremos fazer as coisas com perfeição. Porém, por que queremos tanta perfeição em uma língua se o nosso objetivo não é habitá-la tanto assim? Se a língua se torna apenas mais um ítem no nosso currículo, se é algo para falar que tenho, se não a utilizo tanto e se não tenho tanta utilidade para ela, alcançar a perfeição nela é um capricho.

E não é um defeito nem uma falha de caráter falar de forma imperfeita. Também não quero com isso dizer que você deve se compremeter 100% a tornar a sua língua-alvo algo totalmente totalmente entremeado no tecido da sua vida. Talvez, como eu, você ache o russo uma língua extremamente interessante e bonita, mas talvez você não queira, talvez você nem consiga ver como, fazer o russo ser algo tão intimamente entrelaçado à sua vida que você chegue a _respirar_ russo. Nesse caso, um russo bom o suficiente para se comunicar e para ler textos pode ser adequado.

Entretanto, se você quer se mudar para o interior da Itália e ama de paixão a obra de Dante Alighieri, talvez não haja escolha a não ser tornar-se tão íntimo com o italiano que você passe a ser tão habilidoso nele quanto na sua língua nativa. Ainda assim, isso pode demorar anos.

Falo isso para que você tenha dimensão do quão realista é "falar perfeitamente". Podemos adotar a ideia de que se não falarmos perfeitamente, é melhor nem começar. Pelo contrário, afirmo: é bom que você fale tão bem quanto essa língua que você está aprendendo tem lugar na sua vida. Se ela vai ocupar muito espaço, _e se você quer que ela ocupe_, então falar perfeitamente ou quase perfeitamente pode ser inevitável. Se não, por que, se não por vaidade, você colocaria sobre os seus ombros a pressão de falar com tanta perfeição?

### Como de fato perder o medo de falar

Dito isso, _para falar bem é necessário habitar por muito tempo a língua_. Agora a outra pergunta: **como perder o medo de falar?** Simples: siga as seguintes etapas:

1. Acostume-se a errar, de modo que você não tenha mais medo de ser imperfeito;

Autoexplicativo. Você vai errar. É inevitável. Se você quiser se preparar eternamente para falar de forma correta desde o início, você nunca vai começar. Pule de uma vez, e erre logo.

2. Converse muito, para que com a prática você se sinta mais à vontade em conversar.

A ideia não é que com a conversa você vai falar de forma "mais correta". Já vimos que não é essa a via. A ideia de conversar muito é simplesmente superar a ansiedade de abrir a boca.

3. Converse com o maior número possível de pessoas. 

Se você fala apenas com o seu professor e/ou um amigo, tais interações podem ter um caráter de "casulo". São interações seguras. Procure falar com outras pessoas. A Internet é um bom lugar para isso.

Você não precisa procurar um "terceiro (ou segundo) tutor", nem uma relação duradoura. Há pessoas com quem você fala que você nunca mais falará na sua vida. Algumas interações que você tiver vão ser desagradáveis. Talvez um nativo tente até te ofender por falar a língua dele de forma errada. Faz parte. Você também esbarrará com pessoas doces, que igualmente você pode nunca mais contatar novamente. Também faz parte. Acostume-se a falar com mais do que as pessoas do seu círculo social habitual.

## "Eu já deveria estar sabendo disso"

O perfeccionismo não nos afeta apenas por meio do estabelecimento de um ideal inalcançável: ele também faz com que nos sintamos inadequados por estarmos onde estamos.

Assim, nós podemos estar inseridos na imersão por meses, talvez anos, mas ainda assim errarmos na nossa fala ou escrita com construtos muito frequentes na língua.

Entretanto, existem elementos de uma língua que não são simples só por serem frequentes. Pense na partícula "que" do português: ela está por toda parte, mas não é de modo algum simples. O mesmo se aplica a certos elementos de outras línguas.

Uma outra coisa que pode impedir o domínio de um novo elemento de uma língua é tentarmos compará-lo com um outro elemento da nossa própria. Se eu tento fazer a língua fazer sentido a partir da minha própria língua nativa, eu simplesmente não vou conseguir. Não tente entender uma língua diferente a partir da que você já domina. Cada língua tem uma lógica própria. Pode ser que os conceitos sejam independentes das línguas, em algum grau, mas cada língua tem uma forma única de expressá-los. Procure encarar a língua que você está aprendendo como algo independente da que você já sabe.

Dito isso, repito: a frequência com que algo aparece, ou o quanto algo aparenta ser básico, não implica nessa coisa ser "fácil". **Idiomas não são escadas**, muito menos funcionam como matemática.

Muitas pessoas falam que a matemática é uma língua, e de certo modo ela é mesmo. Porém, a matemática possui algo diferente das línguas naturais: ela procede como que em degraus. Para aprender cálculo você precisa saber álgebra, e para saber álgebra você precisa saber aritmética.

Línguas naturais, como o Português e o Mandarim, não funcionam assim. A língua não é uma escada em que você precisa dominar perfeitamente o tempo presente do indicativo antes de se enveredar pelo futuro do pretérito. Não. A trajetória do aprendizado de uma língua é mais algo como uma espiral: você vai reforçando, incrementando e revisitando o seu domínio em diferentes partes dela de forma contínua. Você começa aprendendo o presente, mas logo você aprende o passado e o futuro; mais pra frente você volta e percebe coisas novas sobre o tempo presente que você não tinha entendido ainda, e isso pode inclusive te ajudar a compreender melhor o tempo futuro; compreender o particípio pode te ajudar a entender adjetivos, de modo que o que você aprende seis meses depois de ter começado a estudar o idioma te auxilia a dominar algo que você viu no seu primeiro mês. 

Aprender língua não é algo linear. Não existe "eu devia já saber disso".

## Práticas errôneas comuns

Os equívocos que vimos acima são erros cognitivos, isso é, são obstáculos no pensamento, na atitude como nós abordamos o aprendizado de língua. Abaixo vamos ver não erros do âmbito da atitude, mas do âmbito da prática, sobretudo na prática da imersão.

### Tirar legendas

Muitas pessoas acham que a legenda é uma espécie de rodinha para a bicicleta, e que se eu aprendo bem com as legendas, as minhas habilidades _listening_ só podem melhorar se eu removê-las! É como adicionar mais peso em um treino na academia, não?

Errado. As legendas são suas amigas, e não são meras rodinhas. Com elas você dá forma escrita ao que é falado, o que, sim, auxilia na sua compreensão, mas também aprimora suas habilidades de leitura. Você aprende a identificar como os falantes da língua normalmente escrevem os sons que eles falam, e a também aprende as inconsistências e exceções às regras de escrita. 

Esse tipo de coisa pode te ajudar a avançar a sua habilidade de leitura _junto_ com a de escuta. Usando legendas, a sua capacidade de leitura auxilia a sua audição, e a sua audição auxilia sua leitura.

Mas ora, é claro que você pode "se desafiar". Entretanto, ao meu ver, esse desafio só deve vir bem mais tarde, quando você já tiver a capacidade de ler histórias e artigos, e quando você estiver entendendo quase tudo o que você escuta _com_ a legenda. Remova as legendas só quando você já estiver entendendo tudo o que está nelas. 

E mesmo assim, não é nenhuma vergonha manter _sempre_ as legendas. Você sabia que [mesmo falantes nativos em inglês assistem filmes americanos com legendas](https://youtu.be/VYJtb2YXae8)?

### Colocar legendas na sua língua nativa

O maior tiro no pé que você pode dar. Claro, pode ser que você _não queira_ estudar agora; que você queira apenas relaxar e assistir um filme. Totalmente válido. Entretanto, se o seu objetivo é _aprender_, colocar a legenda na sua língua nativa vai essencialmente desligar a parte do seu cérebro que se dedica a decifrar o conteúdo da sua língua alvo. [Um estudo](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0158409) investigou justamente isso, e descobriu o seguinte:

1. Se você quer aprender uma língua, assistir filmes nela com legendas nessa mesma língua é melhor do que assistir esse mesmo filme sem legenda.
2. Assistir o filme sem legenda é melhor do que assistir esse mesmo filme com legenda na sua língua.

Ergo, áudio e legendas na língua-alvo são melhores do que apenas áudio, sem legendas, que é melhor do que áudio na língua alvo e legenda na língua nativa.

Conclusão: se o seu objetivo é aprender, no mínimo não coloque legendas na sua língua nativa e idealmente coloque áudio e legendas na sua língua-alvo.

### Usar apenas material que já entendo

Um dos princípios do aprendizado de línguas é o $I+1$ que, lembrando, implica em estudar material ligeiramente superior ao nível que você já domina. 

Não é nenhum problema usar o mesmo material múltiplas vezes. Li certa vez sobre um rapaz que [estudou russo jogando a mesma série de três jogos cerca de 48 vezes](https://www.reddit.com/r/gaming/comments/pcuwrn/i_had_a_friend_learn_russian_through_the_metro/). Existe vantagem nisso se você de fato está sempre aprendendo algo novo (e se você tiver tanta paciência assim).

Mas a familiaridade nem sempre nos traz desafio. Nós queremos sempre estar nos desafiando, pelo menos um pouco. Se eu só fico relendo e reassistindo coisas que eu já entendo 100%, não estou crescendo nada. Se também só procuro material dentro do meu nível atual, também não crescerei nada. O resultado seria ficar eternamente lendo histórias infantis, o que seria, sinceramente, um saco.

Procurar material bom para se aprender é difícil. Pode sim ser necessário e produtivo repetirmos, mas convém que sempre procuremos expandir o nosso vocabulário.

### Praticar imersão apenas depois de "estar preparado"

Esse é um erro fortemente promovido por cursos de inglês. Não raro, existe a ilusão de que o curso "te preparará" para que "só depois" você se arrisque no mundo. Não deve ser assim. Cursos devem ser um suporte, você deve errar por conta própria.

Curiosidade: a palavra "errante" significa tanto "aquele que comete erros" quanto "aquele que vagueia". Você deve ser um agente errante no seu próprio aprendizado. Voe por conta própria. Preparar-se eternamente é nunca agir. A partir do dia 1, da primeira aula do básico 1, já vá errar por conta própria. Faça o que for necessário para se sair bem dentro do curso, mas fora dele experimente de forma livre.

### Usar substitutos à imersão

Imersão consome tempo, mas é a única coisa que de fato traz resultados duradouros. O motivo disso é que, como eu disse anteriormente, para dominar uma língua é preciso habitá-la. A imersão é justamente isso.

Entretanto, ela consome tempo e ela traz ansiedade; queremos estar preparados; queremos até nos preparar para poder ter uma imersão melhor no futuro.

E aí você pode ficar passando por listas de vocabulários, aprender seis mil palavras, estudar tempos verbais e declinação. Tudo isso pode servir de apoio à imersão, mas **sem ela isso é tudo inútil**. Isso é você tentar aprender a andar de bicicleta lendo um manual. Não funciona.

Não tende substituir a imersão. Ela é o cerne da questão. Todo o resto é apenas complemento.

### Usar apenas materiais didáticos

Um subconjunto do equívoco anterior, este pode até ser considerado, sim, um tipo de imersão, _se o material for de boa qualidade_. Há textos de cursos de inglês que são muito bem editados, adaptados e elaborados, e que podem nos ajudar verdadeiramente na nossa busca pelo domínio da língua.

Entretanto, materiais didáticos são frequência **engessados**. Eles nos ensinam formas fixas e um tanto formais de comunicação. "Oi, como vai você?" é uma forma gramaticalmente correta e cumprimentar alguém, mas o que você vai fazer se, tendo aprendido só essa forma de se comunicar, um dia você viajar para a Polônia e um nativo te cumprimentar com algo como "qual é a boa?".

Isso não está no livro. Materiais didáticos são limitados, engessados. Eles tratam a língua como uma série de rotinas e regras fixas, com exercícios que te ensinam apenas uma forma muito restrita de se comunicar e que é normalmente anti-natural e antiquada, além de culturalmente descompassada.

Nunca vi um nativo falando algo como "I'm on cloud nine!" para dizer que estava animado, mas já vi isso em materiais didáticos de inglês. "So-so" para "mais ou menos" é praticamente outro mito: embora correto, eu só vi sendo usado por um nativo da língua inglesa uma única vez, em um contexto muito formal e com um uso extremamente específico. Em nenhum livro didático de inglês eu vi usarem "twelve hundred" para "mil e duzentos", mas já vi esse tipo de linguajar em inúmeras séries de televisão.

Não se prenda a materiais didáticos. Eles não te ensinam a se comunicar como os nativos se comunicam. As gírias estão frequentemente erradas, e a fala é muito roteirizada. Assistir uma sitcom vai ser muito mais útil nesse âmbito.
