# Sistemas de escrita

Nesta página vou procurar mostrar como aprender diferentes sistemas de escrita não é tão difícil quanto parece. É comum que essa seja uma das partes mais fáceis do aprendizado de línguas estrangeiras, inclusive.

Primeiro de tudo, temos que saber que a forma como o nosso alfabeto funciona não é "o certo". É só mais uma das formas como as pessoas podem expressar por escrito as suas ideias. Para um asiático, o alfabeto latino é tão estranho quanto o deles é pra nós.

E sobretudo é a estranheza que é o maior obstáculo, e não a dificuldade. Os sistemas de escrita não são difíceis (em geral), apenas mais ou menos diferentes do nosso. Aprendê-los, porém, não é muito diferente de um exercício de memorização: em geral isso basta. Claro, não é o suficiente que você simplesmente grave os diferentes alfabetos que existem: você tem que utilizá-los.

Uma prática boa para exercitar esses diferentes sistemas de escrita é utilizá-los para escrever as coisas na nossa própria língua. Ou seja, escrever em português, mas usando outro alfabeto. Então segue a primeira dica: tente escrever coisas como frases, seu nome e o nome de outras pessoas, tudo isso nesse outro sistema de escrita. O Duolingo também é uma boa ferramenta para se aprender sistemas de escrita. Reitero: ele pode não oferecer um bom custo-benefício quanto à aquisição de vocabulário, mas para aprender sistemas de escrita ele é muito proveitoso.

Se você é capaz de memorizar uma música, você é capaz de memorizar um novo sistema de escrita.

---

Vamos diferenciar as diferentes categorias de sistemas de escrita, e ver como eles funcionam na prática. Há múltiplos tipos diferentes: alfabéticos, silabários, abjads e logográficos. Há outros além desses, mas vamos abordar apenas esses. Não irei _ensinar_ nenhum sistema por inteiro: intenciono apenas mostrar qual a _lógica_ por trás de alguns deles.

## Sistemas alfabéticos

Os sistemas alfabéticos são aqueles como o latino, o grego e o cirílico. Este último é utilizado para línguas eslávicas, como russo e búlgaro, e é mais semelhante ao nosso do que parece. O nosso alfabeto é o latino, pois o herdamos do império romano, que tinha o latim como língua oficial. É bem fácil aprender estes pois apenas precisamos aprender as equivalências entre letras e sons. 

Vamos utilizar o russo como exemplo. Consideremos a palavra "drama": em russo ela seria escrita драма. O som é o mesmo. É fácil perceber as correspondências: "d" corresponde a "д" e "r" corresponde a "р". 

Há outras diferenças. O russo tem 33 letras, mais do que o nosso alfabeto. A consequência lógica é que não há uma correspondência exata de um alfabeto para o outro. Por exemplo, se eu quisesse transliterar "arara" para o russo, eu escreveria "арара", mas "arrocha" seria "ахоша". Há uma diferença entre "r" (р) e "rr" (х); o som de "ch" é representado por ш. Se eu quisesse escrever "tcharan", eu escreveria "чаран", que mostra que o "tch" é representado por ч, e o n é um н.

Nem todos os fonemas que existem estão presentes na nossa língua. Eles têm uma vogal que não utilizamos: ы. Parece um "b" e um "l" juntos, mas na verdade é uma vogal que parece muito com um "uê" ou "uí". Se você ouvir no Google Tradutor o som da palavra мы ele ficará mais claro. Mas isso também não é um bicho de sete cabeças: de novo, é um simples exercício de memorização.

Assim, vejamos alguns outros exemplos de palavras. Não vou _traduzir_ as palavras, apenas transliterá-las, isto é, escrever palavras da nossa língua utilizando o alfabeto cirílico:

- Banana - Банана
- Trono - Троно
- Discoteca -  Дискотека
- Chanceler - Шанселер
- Salame - Саламе
- Avental - Авентал
- Bisnaga - Биснага
- Sertanejo - Сертанежо

Claro, não vimos todas as letras do alfabeto russo. Há ainda outras peculiaridades a serem aprendidas, mas isso pode dar uma noção do que esperar ao aprender um novo alfabeto, e demonstra como esse processo não é nenhum bicho de sete cabeças.

## Silabários

Sistemas silabários são utilizados em línguas como coreano e japonês. Vamos utilizar o japonês como exemplo.

O japonês utiliza dois sistemas silabários de escrita mais um sistema logográfico. Estes são o _hiragana_ (utilizado para palavras japonesas), _katakana_ (utilizado para palavras estrangerias) e o kanji (símbolos não-fonêmicos que representam conceitos). Utilizaremos aqui apenas o _hiragana_ (pois costuma ser o primeiro que os estudantes de japonês aprendem). Como vamos apenas transliterar palavras, talvez o _katakana_ fosse mais apropriado, mas como ele segue a mesma lógica e o _hiragana_ costuma ser aprendido primeiro, vamos utilizar este último. Veremos a respeito dos _kanji_ na seção sobre sistemas logográficos nesta página.

Em um tal sistema, no lugar de representar letras isoladas, como "K", "A", "E", "I", "O" e "U", representa-se as sílabas compostas por elas, tendo um símbolo diferente para cada sílaba. Por exemplo, os sons "ka", "ke", "ki", "ko" e "ku" seriam escritos か, け, き, こ e く.

Há exceções. No japonês, há as sílabas "na", "ne", "ni", "no" e "nu", mas há também os símbolos isolados para o som de "n" e de cada uma das vogais. Contudo, não se pode juntar eles para formar as sílabas; eles devem ser utilizados em certos contextos. Ademais, há certos sons que nós temos que não existem nessa língua.

Se eu quisesse transliterar a palavra "quindim", eu teria que usar os seguintes símbolos: "ki", "n", "dji" (pois não há símbolo para "di") e "n". Ficaria assim: きんぢん. É simples decifrar estes símbolos: o som para "n" (ん) aparece duas vezes, o que torna mais simples entender que "ki" é き e "dji" é ぢ.

Vamos ver mais alguns exemplos. Não há no japonês símbolos para a letra "s" isolada, nem encontros consonantais com "cr" e "br", então é comum ver outras sílabas em seus lugares. Segue:

- Banana - Ba-na-na - ばなな
- Sabonete - Sa-bo-ne-te - さぼねて
- Biblioteca - Bi-bu-ri-o-te-ka - びぶりおてか
- Tronco - Tsu-ro-n-ko - つろんこ 
- Aristocrata - A-ri-su-to-ku-ra-ta - ありすとくらた
- Brasileiro - Bu-ra-ji-re-i-ro - ぶらじれいろ
- Samba - Sa-n-ba - さんば
- Cascavel - Kasukaberu - かすかべる

É inegável: são muitos símbolos. Considerando que para cada combinação de consoante e vogal há um símbolo diferente, o número de símbolos é necessariamente maior do que no caso das línguas alfabéticas. Há um total de 46 _hiragana_ básicos, mas também há suas versões com diacríticos. Por exemplo, o símbolo da sílaba "ha" は) pode ser modificado para formar os sons "ba" (ば) e "pa" (ぱ), resultando em um total de 71 sons. Sem contar com os _katakana_ e os _kanji_.

Mas não há grande mistério: é apenas um grande número de coisas a se memorizar. Se você consegue memorizar milhares de palavras (e você consegue), você também pode memorizar pouco mais que uma centena de símbolos. A inserção dessas coisas em contexto ajuda: se você procurar aprender palavras (e exercitar escrevê-las à mão!) e não apenas a memorizar as sílabas, você aprenderá mais rápido. Se inserir essas palavras em um contexto significativo, como uma música, tanto melhor. Se você consegue memorizar uma música, você consegue memorizar essas coisas. É apenas questão de ir devagar. Não tente memorizar tudo de uma vez só: separe uns dez por dia e vá acrescentando ao longo do tempo.

O coreano não é muito diferente, mas as letras são lidas em blocos, da esquerda para a direita e de cima para baixo. E há menos (bem menos) símbolos.

## Abjads

Não sei o que costuma assustar mais as pessoas: o japonês e o mandarim ou o árabe. A verdade é que o árabe é comumente utilizado por nós como um exemplo de escrita incompreensível. Memes na Internet que expressam a confusão diante desse sistema de escrita abundam.

Abjads não se aplicam apenas ao árabe. Há outros, como o siríaco e o hebraico. Utilizarei o árabe como exemplo, pois não faço ideia de como funciona o siríaco, e o hebraico é aparentemente bem mais simples que o árabe.

O nome "abjad" vem do alfabeto árabe, em que as quatro primeiras letras são "abjd". 

A primeira característica peculiar deste sistema de escrita é que ele é escrito da direita para a esquerda, e não da mesma ordem que os nossos, mas é apenas questão de se acostumar com a diferença. A segunda é que as vogais não costumam ser escritas, a não ser como "marcações auxiliares". A maioria das palavras não vem com tais marcações, mas costuma-se acrescentá-las a palavras incomuns ou bem específicas, ou em textos religiosos como na Torá ou no Corão. Em hebraico se utilizam certo número de pontos em diferentes posições para representá-las, e em árabe são utilizados traços, círculos ou outros símbolos acima ou abaixo das letras.

Uma peculiaridade do árabe é a maior parte das letras tem duas ou três formas de serem escritas. O que diferencia qual será utilizada é a posição dela na palavra. Se estiver no início será uma forma, se estiver no final, outra, se estiver entre duas outras letras, outra. As letras podem ou não se conectar à próxima ou à anterior.

Vejamos por exemplo o som "b". Ela é representada pelo símbolo ب. Essa curva com um ponto embaixo pode representar os sons "bi", "bu" e "ba". Não há vogais "o" e "e" em árabe, mas há distinção entre vogais longas (aa) e curtas (a). 

Se eu quero escrever "bb" (digamos, para representar "babá") eu o faria da seguinte forma:

- بب

Perceba como as letras se fundiram. O ponto continua embaixo das curvas, mas uma curva se encurtou e a outra se manteve a mesma. Se eu escrevesse "bbb" (algo como "bababa"), isso seria representado como ببب. Uma letra se "encolhe" no meio das outras, tomando a forma de uma "voltinha", enquanto que o ponto continua embaixo dela.

Consideremos agora os sons "t" (ت) e "n" (ن):

A lógica é a mesma. "Tt" (tatá, por exemplo) poderia escrito como  تت, e "ttt" como تتت. "Nn" seria نن e "nnn", ننن. Repare como no caso do "t" há dois pontos e no caso do "n", apenas um. Porém, os pontos ficam sempre _acima_, e não abaixo como no caso do "b".

Vejamos então alguns exemplos. Lembre-se de ler da direita para a esquerda:

- Banana - bnn - بنن
- Batata - btt - بتت
- Bonita (bunita) - bnt - بنت
- Nabo (nabu) -  nb - نب
- Nanica - nnk - ننك
- Arara - Aarr - ارر
- Rato (ratu) - rt - رت

Acima foram apresentadas três sons diferentes: o "A" longo (aa, ا), o "r" (ر) e o "k" (ك). Algumas letras mudam de forma consideravelmente quando colocadas em posições diferentes da palavra. O "A" longo apenas se conecta com letras que vêm _antes_ dela, e nunca após. Por exemplo: "Ba" (با) e "Ab" (اب). O "k" muda de forma peculiar: no caso de "kk", ele é escrito como كك; se escrevo "bknk", بكنك.

No hebraico as letras não se misturam umas às outras, o que facilita a leitura e a escrita. Entretanto, esse sistema de escrita não é tão difícil quanto parece: mais uma vez, é apenas questão de memorizar desta vez não um número maior de letras, mas múltiplas versões da mesma letra. 

O árabe tem a peculiaridade de, apesar de ter poucas vogais, ter múltiplas versões do que nos parece ser a mesma consoante, mas para eles são coisas muito diferentes. Por exemplo, eles têm o "S" que é entoado na ponta da língua, entre os dentes, e o "S" que é entoado no fundo da garganta. Não há tantas diferenças entre esse sistema de escrita e o alfabético, entretanto, salvo duas: 1. você (quase que) só escreve as consoantes e 2. as letras mudam de forma dependendo da posição delas na palavra (no início, no final, entre duas outras letras). 

Claro, não há muito mais letras no árabe do que o que vimos aqui, mas a ideia não é esgotar o conhecimento acerca desse sistema de escrita, apenas mostrar a lógica por trás dele.

## Sistemas logográficos

Deixei por último o mais complexo. Este exemplo se alicerça na parte sobre [Silabários], portanto lê-la anteriormente (se você não o fez) pode ajudar a compreender o que vem a seguir.

Se eu quisesse escrever, em japonês, a frase "eu sou japonês", sem usar _kanji_ (o sistema logográfico embutido na escrita japonesa), eu faria isso da seguinte forma:

- わたしはにほんじんです (watashi-wa nihon-jin desu)

Desmembrando-a, cada parte corresponde ao seguinte:

- わたし (watashi - "eu") 
- は (wa - marcador de tópico; peculiaridade gramatical do japonês) 
- にほんじん (nihon-jin - "japonês")
- です (desu - verbo ser/estar)

Manter as coisas dessa forma, porém, poderia tornar o japonês muito "bagunçado" para ler. Repare como não há espaços entre as palavras. Assim, é necessário empregar os _kanji_:

- 私 - わたし - watashi, "eu"
- 日本人 - にほんじん - "japonês"

O resultado tem a mesma pronúncia, mas outra escrita:

- 私は日本人です

A palavra para "Japão" em japonês é "日本" (nihon). Se a palavra para "japonês" (cidadão japonês/pessoa japonesa) é 日本人 (nihon-jin), podemos supor então que o símbolo para "pessoa" (人) seja pronunciado como "jin", certo? Bom, neste contexto sim, mas há situações em que ele pode ser pronunciado como "hito". Em sistemas logográficos não há correspondência entre símbolo e som, apenas entre símbolo e ideia: o som, a palavra, você tem que aprender de outro modo. Àqueles que estão interessados em aprender japonês ou mandarim precisarão suplementar a imersão com uma forma de dominar um número maior destes ideogramas. Esses símbolos não são arbitrários e há uma lógica interna para eles, mas é necessário muito envolvimento neles para encontrar padrões além da simples memorização. Assim como nos sistemas de escrita por abjad, os ideogramas incomuns costumam vir associados de algum auxiliar para leitura (ao menos no caso do japonês), como _hiragana_ explicando a pronúncia correta do _kanji_. 
