# Cursos e professores {-}

Contratar tutores ou matricular-se num curso possui múltiplas vantagens. É necessário, entretanto, tomar cuidado com certos vícios. Vamos falar primeiro sobre professores particulares e tutores.

## Professores particulares e tutores

Eu acredito que um professor deve ser um tutor, e não um "ensinador de regras". Acaba que frequentemente os professores de língua gostam muito de gramática (eu mesmo gosto muito de gramática -- apenas não acredito no seu potencial didático), e acreditam que a forma _certa_ de ensinar e aprender uma língua é pela gramática.

Os melhores professores, entretanto, quando não nativos, não são aqueles que sabem todas as regras, mas aqueles que sentem plenamente confortáveis com a língua. Se o seu professor não sabe falar (isso deveria ser óbvio), dê meia-volta.

Com isso não quero inimizar sotaques. Sotaque não é defeito. Ele pode ter o sotaque mais "abrasileirado" que você já viu. Isso não importa. Ele precisa, entretanto, ter a confiança e a fluidez para ele próprio ler textos originais na língua que ele ensina, e quando ele for te ensinar na língua ele deve fazê-lo _na própria língua_. Se você pergunta o significado de uma palavra, as melhores coisas que ele pode te dizer, em vez de te dizer a tradução dela, são:

1. Analisar a palavra, quebrando-a em partes, e explicitar o significado de cada parte de palavra; 
2. Apresentar sinônimos da palavra _dentro da própria língua_
3. Apresentar uma história ou contexto em que essa palavra é utilizada, e com isso te ajudar a compreender pelo contexto.

Claro, não é um defeito se ele não fizer isso 100% do tempo. Se está no final da aula e você pergunta o significado de uma palavra, por questão de disponibilidade de tempo ele pode justamente decidir só te dar a tradução; se após múltiplas tentativas de explicar uma palavra pelos pontos 1, 2 e 3 o aluno ainda não entende, pode ser proveitoso fornecer a tradução apenas para economizar tempo. 
Ninguém se sente mais confortável em uma língua do que um nativo. Entretanto, é comum que nativos não tenham muita didática, a menos que eles tenham formação de professor e, mais importante, já falem uma segunda (ou terceira, quarta...) língua. Um nativo que nunca passou pelo processo de aprendizado de línguas dificilmente dará boas instruções. Por isso, se você tiver um tutor nativo, não seria ruim dizer para ele o que você quer, e fazê-lo de forma cordial pode fazer grande diferença. Por exemplo: "você pode falar comigo apenas na sua língua? Você pode tentar me explicar as palavras que eu não entendo na sua língua... pela sua língua?" 

Muitos nativos, de múltiplos países, passam a prestar serviços de tutoria de línguas pra complementar a renda, e não têm formação pedagógica. O ideal, de fato, seria um nativo com formação pedagógica. Um ótimo exemplo disso é no podcast da língua russa _[Russian with Max](https://www.youtube.com/watch?v=YGqD2K1543w)_, em que ele fala em russo do início ao fim e, por reconhecer as palavras em russo que são mais difíceis para os seus ouvintes, as explica usando outras frases, situações hipotéticas e sinônimos dentro do russo, saindo do russo apenas quando não existe uma forma mais econômica de tempo para explicar tais palavras.

Dito isso, certamente vale a pena contratar um nativo para ser o seu tutor, mesmo que ele não tenha a melhor formação pedagógica (ou nenhuma). Nesse caso, entretanto, você vai precisar ter um pouco de assertividade para dizer o que você quer dele. Lembre-se da gentileza.

Quanto aos professores não-nativos, como já falei, o óbvio é que ele precisa falar a língua e precisa falar bem. Mas se você não fala, como é que você vai saber que ele fala bem? Um critério óbvio é a capacidade dele em se expressar com fluidez. O outro é a familiaridade dele com o idioma: se ele tem o hábito de ler no idioma que ele ensina, isso é um bom sinal. 

Mas ele pode ter a melhor desenvoltura e familiaridade com o idioma e ainda assim adotar práticas pedagógicas ineficientes. Nesse caso, não acho que há espaço para você dizer pra ele "adotar outras práticas pedagógicas". **Professor é um bicho meio orgulhoso**. Isso pode ser facilmente tomado como indelicado e arrogante da sua parte (e ele pode estar certo, dependendo da forma que você fala). Dito isso, eu já tive discussões cordiais a esse respeito com alguns alunos. A lógica é a seguinte: o professor deve ter a capacidade de adequar as aulas às suas necessidades, então você pode (e deve) discutir com ele quais são seus objetivos, e ele deve reconhecer o seu nível de fluidez na língua.

O melhor tipo de material didático, ao meu ver, são conversas e textos. Postagens de blogs, notícias, contos, poemas, esse tipo de coisa. O professor que trabalha com você a compreensão de textos que estão _um pouco acima_ da sua zona de conforto está mil anos à frente daquele que te passa exercícios repetitivos de preencher as lacunas com a conjugação correta de um verbo ou coisa do tipo.

E qual é o problema com isso aqui? Acontece que, diante da percepção de que você _fala bem_, mas erra em coisas "básicas", um professor pode querer adotar a infeliz prática de "reforçar o básico" com você. E eis que você está lá, já consegue ler textos complexos, mas comete alguns erros na hora de falar, e ele te coloca para estudar material extremamente básico, do tipo dos "verbo _to be_" e "pronomes pessoais". O problema é que ele pensa que a língua é uma habilidade igual matemática, uma escadinha cujos degraus devem ser plenamente dominados antes de passar pro próximo.

A questão é que aprender uma língua não é um processo linear, mas uma espiral. Querer fazer das línguas um processo linear, uma escadinha igual aritmética -> álgebra -> cálculo, simplesmente não funciona.

Assim, a aula com um professor _deve também_ ser imersão. Mas se eu já pratico imersão por conta própria, por que é que eu vou querer praticar imersão com um professor? Ora, porque a imersão com o professor é _feita para você_, como uma roupa sob medida. As conversas vão ser feitas de modo que você as compreenda, e os textos devem ser compreensíveis por você com um pouco da ajuda do professor. Se você não entende nada, aí está difícil demais e as lições têm que ser moduladas. Por outro lado, você não precisa compreender tudo: ele deve, pouquinho por pouquinho, ir ampliando o escopo da sua compreensão.

Dito isso, não é um problema, necessariamente, se vocês trabalharem com livros didáticos, desde que você esteja no nível desses livros didáticos. Ruim seria se você, lá na frente em boa parte da língua, fosse forçado a dar meia volta para garantir "degraus passados" estão adequadamente reforçados. A língua não é uma escada, mas uma espiral. Os degraus passados vão ser reforçados ao seguirmos em frente.

## Cursos

O maior benefício dos cursos é a socialização.

Há pessoas que não gostam de fazer as coisas sozinhas. Normal: o ser humano é um animal social. Quer ir pra academia? Vai com amigos. Quer praticar um esporte? Só com amigos; e assim por diante. Algumas pessoas só sentem motivação de ir para a faculdade por conta dos amigos que têm lá. O mesmo se aplica ao estudo das línguas.

Então os cursos têm esse motivador inegável: lá você pode conhecer pessoas, fazer amigos, socializar, e praticar tanto com professores quanto com seus colegas.

O método que eu tenho exposto nessas páginas aqui não é _antagônico_ aos cursos. Você pode muito bem utilizar os dois juntos, e adiciono: um vai beneficiar o outro. Os estudos vão auxiliar na imersão, e a imersão vai auxiliar nos estudos.

Mas existem algumas coisas que eu não gosto nos cursos. Elas não os arruinam, mas acho que é importante sabê-las.

A primeira é que os cursos comumente se vendem como as únicas ferramentas necessárias. Eles promovem a ideia de que tudo o que você precisa fazer é entrar no curso, ir do Básico ao Avançado e, tendo-o terminado, você saberá falar a língua. Isso é falso. 

Isso pode acontecer. Se você for muito dedicado, é provável que aconteça. Todavia, é muito comum que ao terminarem o curso no "Avançado", muitos alunos estão na verdade no "Intermediário".

E o motivo pelo que isso acontece é que os cursos preparam as pessoas eternamente, isto é, levam elas a crer que elas devem terminar o curso _e depois_...

Óbvio, isso não é feito por todo lugar, e nem por todos os professores. Para ser sincero, os professores costumam ser contra essa narrativa de que "o curso basta", mas por uma série de fatores eles nunca falam isso. Primeiro porque isso pode, de certo modo, diminuir a credibilidade do trabalho deles (ora, isso aqui não é o suficiente?), e segundo porque isso pode diminuir a credibilidade da empresa em que ele trabalha (ora, essa empresa não tem um trabalho bom o suficiente?), e terceiro porque às vezes simplesmente não há tempo (ou priorização) para abordar esse detalhe.

A verdade é que o trabalho de **nenhum professor**, nem o de **nenhum curso**, basta. Você precisa andar por conta própria, e os cursos e professores vão te levar apenas até certo ponto. Não subestime esse "até certo ponto", pois ser levado, digamos, até o intermediário já é muito bom. A dificuldade de muitas pessoas costuma ser simplesmente começar, ter uma diretriz.

Mas você precisa, você mesmo, mergulhar.

Se os cursos não agissem como casulos, tão focados em manter o aluno dentro de si próprios, e em vez disso estimulassem os alunos a, com o suporte que eles dão, explorarem as diferentes línguas por conta própria, eles seriam muito mais eficientes. A maioria das pessoas poderia sair do Avançado de fato... Avançadas.

É necessário que você tome uma postura ativa na sua própria educação. Cursos e professores fornecem uma base, mas a base serve como uma plataforma, na qual você não deve ficar parado. 

Dito isso, existe mais uma coisa nos cursos que precisa ser tomada em conta: a socialização.

Pera, não foi por aí que começamos. Sim! Mas o que funciona como motivador pode também servir como empecilho. Todavia, isso conta apenas para os que se dedicam pouco.

Por anos dando aula como professor de inglês eu vi o seguinte padrão acontecer: alunos pouco dedicados que fazem amizade com outros alunos igualmente pouco dedicados tendem falar tão bem quanto o mais confiante dos dois. Quer dizer: o cego mais ousado é quem guia, mas os dois caem no buraco.

Na página sobre [o desenvolvimento da fala][Prática: _language parents_], eu falei sobre os vícios de linguagem que podem surgir quando queremos falar cedo demais. Acontece que nos cursos nós podemos pegar os vícios de linguagem uns dos outros. Isso tende a ser remediado com a educação, mas tende a ser agravado pela insegurança e pela preguiça.

Os **melhores** cursos se baseiam na chamada _abordagem comunicativa_, que tem a meta de tornar a educação mais divertida. Ela é inegavelmente engajante e efetiva, mas esse objetivo tem efeitos colaterais. Parte do marketing por trás desse método é que _você já fala desde o primeiro dia_. Quem é que não vai querer isso, certo? Você tem um retorno rápido para o seu investimento.

Mas pra fazer com que isso seja possível, os alunos se tornam os principais tutores. O professor é extirpado do seu papel de transmitir a língua e se torna uma espécie de maestro, coordenando jogos por meio dos quais os alunos vão desenvolvendo suas habilidades comunicativas na língua estrangeira. Certamente isso é melhor do que uma aula focada apenas em gramática na qual apenas o professor fala -- essas são terríveis, é inegável -- mas o melhor recurso que há ali é deixado de lado: o professor. 

Os **melhores** cursos acreditam que no seguinte. Há duas variáveis interessantes numa aula de inglês: "Teacher Talking Time (TTT)", ou "tempo de fala do professor", e "Student Talking Time (STT)", ou "tempo de fala do aluno". Existe nos cursos que para que a aula seja boa, é necessário que $STT>TTT$, que os alunos falem mais do que o professor, e quanto mais melhor. Na língua-alvo, claro.

Uma das crenças por trás disso é a de que os alunos devem _exercitar_ a fala para desenvolvê-la. Essa teoria ignora a importância que existe _no tempo_ que o aluno passa com a língua, inclusive _fora do curso_. Uma outra é que quando o professor abre a boca para falar, ele o faz para instruir, para ensinar regras e métodos. Existe aqui uma falsa dicotomia entre "alunos falando" e "professor que só ensina gramática".

Uma escola que faz um bom trabalho de quebrar com essa dicotomia é a _Schola Classica_, que ensina línguas antigas (grego e latim). [Aqui](https://youtu.be/vhKL_H4Mqvs) você pode ver um exemplo de um vídeo em que o professor _fala muito_ e também há _muita aprendizagem_: a aula é **toda** imersão.

O professor é o melhor recurso da sala de aula, _pois_ (é óbvio) _ele é que melhor fala a língua_. Não é porque ele pode dar instruções, mas porque ele pode funcionar como _language parent_. Meu Deus! Eu acho incrível, tristemente incrível, como esse fato pode ser ignorado.

Eu não acho que o modelo do Schola Classica (do vídeo de dois parágrafos atrás) é perfeito. Eu acho que ele ainda pode ser melhorado, mas ele me parece mais eficiente para o aprendizado 

Assim, a abordagem comunicativa comete o erro de pensar que os alunos devem tatear juntos pela língua, descobrirem-na juntos, com a mínima quantidade possível de instrução. É um método um tanto romântico nos seus fundamentos, certamente divertido na sua prática, mas mais eficiente no marketing do que na entrega dos resultados. Repito: o comum é que os alunos saiam do "avançado" como "intermediários". Claro, há variação: há aqueles que saem do "avançado" realmente avançados... E aqueles que saem apenas pouco acima do básico.

Mas eu repito: os melhores cursos de inglês no mercado utilizam esse método. Por serem os melhores eu não quero dizer que são os melhores possíveis. São os melhores que estão disponíveis. É difícil encontrar um método mais rentável do que este, de verdade. E com todos os seus defeitos, ele é o que melhor entrega resultados _dos que_ foram aplicados em cursos em larga escala. Os cursos são "uma camisa para todos os tamanhos". Se você veste M, P ou GG, que pena!, você ganha uma camisa M. Apertado? É o que tem. Grande demais? É o que tem. O método do qual eu estou falando nestas páginas não é feito para "um só tamanho". Ele nem sequer _funcionaria_ se se tentasse fazer algo para um só tamanho! A prerrogativa dele é que é necessário, em todos os casos, em todas as aplicações, adequar o método ao usuário.

E por isso é tão difícil "fazer um curso" com ele.

Sabendo disso, não pense que eu me oponho a cursos. Eu acredito verdadeiramente no potencial deles e reconheço que em certos casos, como para quem só sente motivação quando faz as coisas com amigos, ele pode ser _o único método_ que funciona. No que eu não acredito é na ideia que os cursos vendem: _a de que eles bastam_.

## Resumo




