# O papel da gramática {-}

## Por que eu deixei a gramática por último

A gramática serve para dar forma ao conteúdo. Este, por sua vez, é o que nós adquirimos por meio da imersão: toda a compreensão intuitiva que temos por conseguirmos compreender o significado e o uso de certas frases devido ao contexto em que elas se encontram.

Ora, se a gramática tem uma elevada capacidade de nos dar um melhor domínio sobre o que já compreendemos em algum nível, é claro que a imersão ajuda na compreensão da gramática.

Mas pode a gramática ajudar na compreensão do conteúdo no qual nos imergimos? Certamente. Mas a gramática, no tocante à habilidade de falar e escrever na língua, serve muito mais como uma ferramenta crítica e corretiva do que criativa. Isso é muito bom para editar um texto, mas não para escrevê-lo.^[Pode parecer uma contradição, mas _escrever_ e _editar_ são processos diferentes. A edição é um processo de crítica do que foi escrito; é onde você refina, conserta e critica. A gramática tem esse valor. Se você quiser "refinar, consertar e criticar" a sua fala em tempo real, o resultado é que você se verá calculando, gaguejando e fazendo longas pausas, o que é indesejado para muitos aprendizes de línguas estrangeiras.] A gramática é muito bom para formatar, mas para dar forma a algo, é necessário primeiro _ter algo_ a que dar forma. Quanto mais cedo a gramática é inserida[^Se o intuito de estudá-la é aprender uma nova língua.], menor o custo-benefício.

O problema é que estudar gramática requer um esforço muito maior do que a imersão por si própria, e o ganho obtido com a imersão, ao meu ver, é maior do que o ganho obtido com o estudo da gramática. Deixe-me repetir: _certamente_ estudar gramática auxiliará na nossa compreensão durante as práticas de imersão. Contudo, quando o objetivo é a aquisição, a imersão é a _via direta_. A gramática é portanto uma via indireta. Ela funciona muito como um suporte que nos ajuda na busca, mas não é ela mesma a busca. Pouco se encontra na gramática: ela só explica o que já foi encontrado, ou nos ajuda a compreender um pouco mais o que encontramos.

Por que eu acho tão importante frisar isso aqui? Porque existe um preconceito corrente na mente de estudantes e professores, e inclusive entre estudantes que nunca pararam para estudar um idioma, de que o meio para aprender a falar uma língua é estudando gramática. "Se eu memorizar todas as regras, então saberei falar a língua". Muito material didático, muitas formações de professores, e muitas horas de estudantes são devotadas ao método `Gramática+Vocabulário`.

A verdade é que se nós memorizarmos o dicionário inteiro e, junto com ele, todas regras gramaticais, nós _ainda_ não saberemos falar a língua. A razão para isso é que conseguir entender e se comunicar em um idioma não é idêntico a conhecer todas as palavras e todas as regras, mas sim a saber como as palavras e as regras dançam juntas -- e elas fazem isso de muitas e muitas formas, por vezes até mesmo contraditórias.

É um conhecimento intuitivo. Como eu falei algumas páginas atrás, _é um gingado_. E esse gingado só se adquire através da experiência e da experimentação. O dicionário e a gramática não são idênticos à língua. Eles são partes, e o todo é diferente da mera soma das partes. _Compreender as partes_ de forma alguma pode te prejudicar, mas não é possível ir somando um a um até chegar ao todo.

Além disso, as regras das línguas não são todas documentadas. O que, você acha que pegar e ler uma gramática do início ao fim vai te familiarizar com todas as regras? Não vai! Há muitas regras que escapam os próprios gramáticos! Há regras para línguas que são faladas há séculos que estão sendo documentadas _hoje_! E mesmo assim, as pessoas falam a língua e usam essas regras corretamente sem nem saber que elas existem.

### Um adendo

Se você estiver aprendendo uma língua antiga, como o grego ático ou o latim, aprender por imersão não será opção. Neste caso você **precisa** aprender gramática. Não tem como deixar isso para depois.

## Por que aprender gramática

O propósito deste site é ensinar _como_ adquirir uma língua, como ser capaz de _falar nela_ e _compreender o que é falado_. Eu não acho que a gramática tem um lugar muito grande nesse processo, mas eu não acho que devemos deixar a gramática de lado. Eu não sou contra a gramática, apenas acredito que o papel dela seja outro.

Há duas grandes vantagens para estudar gramática. A primeira delas é aperfeiçoar a nossa compreensão _sobre a_ língua. Quando aprendemos a língua por imersão, nós adquirimos uma compreensão intuitiva das regras, e pode acontecer que nós vacilemos aqui e ali na hora de nos expressarmos; pode ser que a nossa estrutura esteja um pouco cambaleante. Assim, a gramática pode servir para _aperfeiçoar_ a nossa compreensão _sobre a_ língua e, principalmente, tornar o edifício da nossa compreensão do idioma mais sólido. O que ela nos dá é mais segurança. Após termos feito uma escultura de argila ela se mostra maleável. Essa maleabilidade pode ser por vezes indesejada, e então a gramática opera como o forno que dá firmeza à nossa construção. Repare, entretanto, que aqui nós _já temos_ uma construção: queremos apenas torná-la mais firme.[^Mesmo nestes casos, quando a estrutura cambaleia, insisto que quando o nosso desejo é aperfeiçoar a nossa produção e criatividade _com fluência_ o melhor procedimento é _mais imersão_. O poder da gramática aqui não é o de falarmos espontaneamente com maior graça e de forma mais correta, mas sim a capacidade de criticarmos melhor o que produzimos. Podemos perceber melhor os nossos erros de fala e editar melhor os nossos textos. Se quisermos corrigir esses vícios que ocorrem no momento da saída, entretanto, temos que ler e que ouvir mais.]

A segunda vantagem em estudar gramática é aperfeiçoar a nossa retórica e a nossa precisão. Isso pode parecer idêntico à primeira vantagem, mas a diferença é sutil. A primeira vantagem citada tem a ver com _segurança_, enquanto essa tem a ver com _intenção_. Compreender mais sobre a gramática da nossa língua nos permite submeter a língua à lógica, o que nos permite eliminar a ambiguidade (ou ser ambíguo de propósito).

A gramática nos permite ser mais perspicazes e mais organizados. No Brasil, as pessoas não têm um domínio muito bom da gramática da língua portuguesa (ou da ortografia, ou do vocabulário). Isso é triste. Mas isso é triste não exatamente porque as pessoas não sabem diferenciar uma oração coordenada de uma subordinada, mas sim por causa dos resultados dessa falta de compreensão.

_Língua é poder_. Geralmente quando ouvimos esse enunciado, ele vem da boca de pessoas que querem relativizar a língua e falar sobre coisas como "preconceito linguístico". Não vou entrar nesse mérito agora: é óbvio que existe coisa tal como preconceito linguístico e opressão oriunda dele, mas eu não acho que isso é motivo para flexibilizarmos (em excesso) a língua.

Afinal de contas, se língua é poder, a melhor coisa a fazer se queremos promover igualdade e ir contra a opressão não é erodir as regras da língua, mas sim socializar a profunda compreensão dela. Se você não conhece bem as regras da sua língua, vai ter alguém que conhece -- um advogado, uma empresa, uma pessoa com intenções que você ignora. Não adianta, portanto, falar de opressão por meio da língua e com isso implicar que devemos rejeitar a norma culta, que devemos falar no tribunal tal como falamos no boteco ou que devemos escrever redações e currículos da mesma forma que digitávamos no MSN antes de 2010 (com _emoticons_ e tudo mais). Pelo contrário: compreender a sua língua por dentro e por fora é tão (ou mais) importante quanto compreender a Constituição do seu país. Uma vírgula em um lugar estratégico e aquele advogado é o novo dono do seu carro.

Conhecer gramática, portanto, não tem a ver com aprender a língua. Tem a ver com espremer dela as suas capacidades mais específicas e ocultas, e que são as últimas a serem conhecidas. Tem a ver com influenciar o mundo ao redor de si e a compreendê-lo melhor. Tem a ver com organizar os próprios pensamentos e a ser adequadamente eloquente.

Língua não é só uma forma de emitir e receber informações, mas uma forma de agir no mundo. Essa ação deliberada tem como fundamento a gramática. 

Quando nós aprendemos uma palavra nova, nós somos capazes de expressar algo novo. "Algodão" é melhor do que "coisa macia e branca que vem de (ou é) uma planta". Esse é um exemplo bem concreto, mas o real valor disso reside quando caminhamos para o abstrato.

Os hindus possuem múltiplas palavras para "espírito" e "alma". Nós temos apenas essas duas, e às vezes ainda misturamos elas com conceitos como "intelecto", "intuição" e, quando queremos ser chiques, falamos de "nous" (que a gente importa do grego). Para nós, "espírito" pode ser uma série de coisas: um estado de ânimo, uma atitude, a alma (sic) de uma pessoa morta. Nós já temos poucas palavras para falar dessas coisas e nós ainda as confundimos entre si. Os hindus conseguem, portanto, discursar com muito mais detalhe, precisão e clareza sobre essas coisas do que nós. Eles conseguem chegar em lugar que nós não chegamos.

Uma palavra nova é um lugar novo, é uma ideia nova. Palavras são lugares novos descobertos no nosso mapa, e ao mesmo tempo são as trilhas que temos para alcançá-los. As palavras, quando compreendidas, nos permitem ver partes de nós e do mundo que anteriormente não conhecíamos; elas dão colorido às partes que anteriormente estavam sem cor.

Se as palavras dão cor e acesso a lugares novos, a compreensão gramatical nos permite ver as cores com maior definição e a entrar e sair desses lugares de forma mais intencional. Sem ela nós podemos ter uma compreensão intuitiva da forma como as cores interagem, mas às vezes elas vão se mesclar. Nós podemos muito bem tatear o nosso caminho pela língua, mas é melhor ter passos firmes.

Portanto, não despreze a gramática. A função dela não é te fazer aprender uma língua, mas sim navegar mais eficientemente e precisamente pelo mundo.  
## Como aprender gramática

Se o seu intuito é aprender a falar um idioma novo, todas as regras que você precisa para conseguir isso podem ser adquiridas mais ou menos por osmose.^[Osmose é o processo de passagem passiva (sem gasto de energia) de líquido entre uma célula e o meio em que ela se encontra a fim de igualar o nível de concentração de um dado soluto (como sal) entre célula e meio. A analogia aqui é que, tal como na osmose, não há investimento de energia para aquisição das regras no aprendizado de línguas: o simples processo de imersão e a compreensão sucessiva e crescente dos enunciados na língua nos faz gradualmente adquirir uma compreensão intuitiva das regras gramaticais envolvidas.] O simples fato de estarmos passando tempo com a língua vai nos conceder uma certa intuição acerca das regras. Só com essa osmose e a devida insistência nós podemos adquirir a capacidade de compreender textos complexos e eruditos e a entender e produzir discursos bem feitos.

Porém, se a sua intenção é ir além disso e de fato usar a língua como um _instrumento de poder_, então cabe que você estude gramática.

Eu não acredito, entretanto, que você precise fazer isso para cada língua que você aprende. Talvez seja necessário fazê-lo caso você saiba línguas muito (muito) diferentes entre si, mas a função da gramática é simples: conectar as partes da língua entre si de forma coerente, intencional e lógica (exceto quando a intenção é, de forma deliberada, violar a lógica e a coerência). Com ela, submetemos a língua à lógica e ao mesmo obedecemos à peculiaridade do próprio sistema lógico da língua.

A lógica é uma só, mas cada língua tem uma forma diferente de aplicá-la. Esse é o tipo de coisa que você aprende com a imersão. Mas se você já conhece o rigor da lógica da linguagem em uma língua, você poderá facilmente vê-lo em outras línguas.

Vejamos um exemplo: algumas línguas são declinadas. Isso quer dizer que os substantivos, adjetivos e outros construtos são flexionados assim como verbos (embora para representar outras funções). As diferentes formas como uma palavra pode ser declinada são chamadas de "casos".

Se nós aprendermos o "caso genitivo" no latim nós seremos capazes de enxergá-lo muito bem no português e no inglês, muito embora essas línguas não tenham casos. O motivo por trás disso é que embora as regras da línguas sejam diferentes, a função é a mesma. As línguas fazem com frequência a mesma coisa sob formas diferentes: se você aprende a fundo uma dessas formas, você mais facilmente consegue vê-la onde quer que ela esteja, mesmo que por outra roupagem.

Assim, é possível ver a mesma coisa sendo feita em diferentes construtos gramaticais de diferentes línguas, como o apóstrofo possessivo no inglês, a contração da preposição "de" e o artigo "o" no português e o caso genitivo no latim:

- The world's soul
- A alma do mundo
- Anima mundi

A mesma relação de posse é expressa em cada um desses exemplos. Conhecer uma facilita o reconhecimento das outras. Você não precisa reaprender a andar de bicicleta toda vez que compra uma bicicleta nova.

Como então aprender gramática? Eu acredito que o verdadeiro custo-benefício em aprender gramática está _na primeira vez em que se a aprende_. Sempre haverá ganho em fazê-lo, na língua que for, mas se você já conhece a gramática de uma língua, aprender a da segunda te dará ganhos reduzidos. 

Isso porque você não quer aprender "as regras da língua". Se a língua não for antiga (como falei acima), você pode adquirir essas regras mais ou menos passivamente. Quero tratar aqui de aprendizado de regras gramaticais explícitas, e para isso eu acredito, sinceramente, que vale mais a pena estudar a fundo as regras gramaticais da sua língua nativa -- suponho que o português -- do que qualquer outra. O melhor procedimento para isso é analisar textos reais com o auxílio de uma gramática de referência ou didática; uma ótima alternativa é fazer um curso de gramática da língua portuguesa.

Portanto, eis aqui a ironia deste trabalho: logo no final de um site que é todo voltado para aprender línguas estrangeiras eu te convido a se aprofundar no português.[^Há partidários do aprendizado da língua latina no lugar do estudo explícito do português. Há um motivo peculiar para isso: séculos atrás existia uma identidade entre "gramática" e "latim". Os escritores clássicos (como Camões) não estudavam suas línguas particulares, mas sim o latim. As pessoas iam para escolas de gramática e o conteúdo programático dessas escolas era, bem, latim! E isso não apenas em lugares como Portugal e Itália, que falam línguas descendentes do latim, mas até mesmo em países como a Alemanha, que de latino não têm nada.] Sim, e o motivo disso é o seguinte: compreender bem e a fundo o português vai te ajudar a compreender melhor outras línguas, principalmente se elas forem línguas ocidentais como a nossa.
