# Sistemas de escrita {-}

Nesta página vamos abordar o "problema" dos sistemas de escrita. Para muita gente, aprender um alfabeto diferente parece um grande obstáculo; muitos postergam aprender uma língua do seu interesse em grande parte pelo fato de ter que aprender um novo sistema de escrita. Outras pessoas de alguma forma ficam meses estudando uma língua só pelos sons, sem nunca buscar compreender como funciona o sistema de escrita na língua em questão.

Existem múltiplos sistemas de escrita diferentes, e é possível criar "grandes categorias" de tais sistemas. Por exemplo, existem os sistemas alfabéticos, como o nosso, que também são adotados pelas línguas eslavas (como russo) e pelo grego, além de outras línguas; existem os abjads, no qual se encontram, entre outras, o árabe e o hebraico; existem as línguas logográficas, como o mandarim e parte do japonês, e existem os silabários, do qual o japonês também é um exemplo.^[O japonês é peculiar pois ele utiliza um sistema logográfico e silabário ao mesmo tempo.]

Não existem apenas esses quatro tipos de sistema de escrita, mas uma boa parte das línguas se encontra nessas categorias.

Vamos falar primeiro do elefente na sala: o sistema logográfico. Desses, concedo que o mais complexo são os sistemas logográficos. Existe toda uma lógica interna para eles. Apesar de você ter uma "imagem específica" para cada palavra, cada um dos desenhos que compõe os ideogramas é composto de partes, de "radicais". Não sou particularmente versado em línguas desse tipo, mas posso dizer com segurança que não é literalmente um símbolo totalmente novo e único para cada palavra, mas cada palavra é escrita como um símbolo composto de partes que são reaproveitadas entre múltiplas palavras.

Dito isso, vamos explorar duas formas de escrita diferentes aqui, só para ver que elas não são nenhum bicho de sete cabeças. Vamos abordar o alfabeto cirílico e o sistema árabe de escrita.

## Alfabeto cirílico {-}

Esse é um sistema de escritom muito semelhante ao nosso e pode nos ser útil para aprendermos uma nova e diferente forma de escrever, que ao mesmo tempo também é relativamente fácil.

O alfabeto cirílico, na sua versão russa, tem 33 letras. Não vamos aprendê-lo em detalhes: quero apenas que você entenda como ele funciona e perceba como ele é simples. Você pode esperar por uma experiência muito semelhante caso você queira aprender, digamos, grego.

Vou escrever a seguir uma série de palavras em português e então as transliterarei para o alfabeto cirílico. Veja bem, não são traduções: estou apenas escrevendo a mesma palavra, com a mesma pronúncia, em diferentes alfabetos.

1. Bola - Бола
2. Banco - Банко
3. Banana - Банана
4. Manuel - Мануэл
5. Dado - Дадо
6. Dardo - Дардо
7. Jorge - Жорже
8. Disco - Диско
9. Discoteca - Дискотэка
10. Pai - Паи
11. República - Република 
12. República Tcheca - Рэпублика чека
13. Xampu - Шампу
14. Escola - Эскола
15. Escolha - Эсколья

---

De novo, essas não são palavras russas, mas sim palavras em português escritas com o alfabeto russo. Não foram abordadas todos os sinais neste breve exemplo, mas se você analisar palavra por palavra, letra por letra, você verá que são apenas os mesmos sons sendo escritos com sinais diferentes. É questão apenas de se acostumar com esses novos sinais, o que, sinceramente, é algo que pode ser conquistado facilmente em um período de mais ou menos uma semana. Talvez menos.

Existem nesse alfabeto alguns signos que não possuem análogo no nosso. Por exemplo, o "sinal fraco" (ь) e o "sinal forte" (ъ) não têm sons, mas sim alteram o som da letra que vem antes deles. Nós temos cinco vogais, eles tem cinco pares de vogais: a, ia (а, я); e, ie (э, е); i, ii (и, й); o, io (о, ё); u, iu (у, ю). Eles também têm algumas consoantes diferentes, como ш e ч, com som respectivamente de "sh" e "tch". Há sinais diferentes com sons parecidos com os nossos (exemplo: s equivale a с; g equivale a г; j equivale a ж) e sinais iguais com o mesmo som (т, м, к).

É só questão de se acostumar com uma roupagem diferente.

## Árabe {-}

Existem múltiplas línguas árabes. Algumas têm sinais que não existem em outras, sons que não existem em outras, mas todas remontam ao chamado "árabe clássico". O sistema de escrita do árabe é um "abjad". O hebraico usa um sistema semelhante, ainda que com signos diferentes. Entendo muito mais de hebraico do que de árabe, mas como o árabe é, às vezes humorosamente, utilizado como exemplo de "língua indecifrável", vou expor aqui algumas diretrizes para começar a entender como esses sistemas de escrita funcionam.

Em um abjad, diferente de em um sistema alfabético, não se escreve todos os sons da palavra. Boa parte das vogais são deixadas de fora. Não raro, as únicas vogais que são escritas, quando são, são as iniciais e, às vezes, as finais. Na palavra "abacate", escrever-se-ia apenas "abcte" ou "abct". 

Como é que os falantes de línguas árabes sabem como pronunciar a palavra? Simples: eles a reconhecem e entendem o contexto. Eles não precisam das vogais no meio da palavra. Entretanto, eles usam certos sinais auxiliares, na forma de traços e curvas, em palavras menos comuns para auxiliar na compreensão.

Outra coisa que torna o árabe de difícil compreensão é que as letras mudam de forma dependendo da posição delas nas palavras. Vejamos alguns exemplos a seguir:

Consideremos a letra "b". Em árabe, o sinal análogo dessa letra é "ب", uma curva com um ponto em baixo.

"ب" tem o som de "ba", "bi" ou "bu", dependendo do contexto. Se eu quiser escrever "baba", eu simplesmente escreveria "بب".

"بب". Isso é análogo a apenas escrever "bb". Mas perceba como a mesma letra, no início da palavra, ganha uma versão reduzida. Se eu quisesse escrever "bababa" escreveria "ببب". No meio, ele ganha também outra versão. Ela é reconhecível pela posição do ponto, que fica embaixo.

Consideremos agora a letra "n", que em árabe é "ن". Agora meio que invertemos. "Na" seria "ن", "nana" seria "نن" e "nanana" seria "ننن".

De modo que "banana" seria escrito "بنن". Três curvas: uma com um ponto em baixo e duas com um ponto em cima.

Consideremos agora a letra "t". Em arabe, ela seria "ت", uma curva com dois pontos em cima. Se quero escrever "tata", "تت"; se quero escrever "tatata", "تتت".

Batata: بتت
Bonita: بنت

Em "batata" temos uma curva com um ponto em baixo, e outras duas curvas com dois pontos em cima cada. Em "bonita", uma com um ponto em baixo, uma com um ponto em cima e uma outra com dois pontos em cima.

Claro, nem tudo em árabe é curva com ponto. O "k" é um "ك", e kaka é "كك", e kakaka é "ككك".

Assim, "cabana" é "كبن".

---

Podemos ver que a escrita árabe é mais desafiadora do que a escrita russa para nós. Ela é difícil porque é muito diferente. Para um falante nativo de hebraico, compreender o sistema de escrita árabe é bem mais simples. Nós vimos apenas quatro letras aqui; há 28 no abjad árabe. Entretanto, a minha ideia aqui foi mostrar que existe uma lógica interna para essas línguas, e que tal lógica não está além do seu alcance. 

## Conclusão {-}

Se você quer aprender uma língua nova, não deixe um sistema de escrita diferente te impedir disso. O árabe pode parecer difícil, mas a verdade é que ele é apenas _muito diferente_. Com algumas semanas de dedicação é totalmente possível e factível dominar completamente um sistema de escrita desses.

Línguas logográficas como o japonês e o mandarim podem exigir mais esforço, mas se o seu desejo é aprendê-las, não deixe que o sistema de escrita seja um obstáculo no seu caminho; faça dele uma _ferramenta_! Muitos, erroneamente, tentam burlar o caminho; tentam aprender a "falar japonês" sem aprender a "escrever japonês". Não faça isso! Por mais difícil que seja, compreender pelo menos o básico de um tal sistema de escrita vai te ajudar muito, e vai te ajudar a compreender mais o material com o qual você pratica a imersão.

Para deixar você com uma dica prática: experimente escrever _na sua língua_ com o "alfabeto" que você quer aprender. Por mais estranho que isso seja, é uma prática útil para fixar o aprendizado. Por fim, se o **Duolingo** serve bem para alguma coisa, é para aprender novos sistemas de escrita. Acredito que ele pode ajudar de verdade neste campo.
