# Apêndice {-}

## Sobre o autor

Meu nome é [Paulo](https://www.instagram.com/trazodone). Sou psicólogo formado pela UERJ e tenho dado aulas de inglês desde 2016, tanto em curso quanto como professor particular.

Além disso, há anos nutro o gosto por aprender línguas por conta própria, por prazer. Além do inglês, que aprendi usando este mesmo método que aqui divulgo, e no qual tenho um certificado nível C2 (o maior nível possível de acordo com a CEFR), também me aventurei pelas seguintes línguas: russo, francês, espanhol, grego antigo, hebraico, latim. Em russo e em francês eu me comunico razoavelmente; espanhol todo brasileiro domínio na forma de "portunhol", mas consigo ler textos clássicos na língua. Quanto às outras três, eu só consigo ler e em algum grau ouvir. Falar, só algumas frases.

Por conta disso, estou sempre buscando como melhor aprender línguas, para tornar o processo mais eficiente para mim, para meus alunos e quaisquer outras pessoas que eu puder ajudar nesse processo.

## Motivo por trás deste site 

Não fui eu que inventei este método. Há décadas ele é trabalhado e divulgado por pesquisadores como Stephen Krashen. Em outros países, há pessoas de fora das universidades que também falam abertamente a respeito desta forma de aprender. Mesmo no Brasil eu não sou o primeiro a divulgá-lo.

Todavia, nem todo mundo tem acesso ao material em inglês acerca deste tema, e o material em português que eu encontrei está, em geral, em formato de vídeo... e um tanto desorganizado. 

Esse foi um dos motivos (ou antes uma das motivações) que me levaram a escrever esse site. 

Mas o motivo principal é o seguinte: inúmeras vezes eu estive com pessoas que demonstraram interesse em aprender línguas, e eu não tinha nenhuma referência que eu pudesse enviar para elas e dizer: "aqui está tudo o que você precisa saber". E isso me incomodava. Logo, eis o site. 

Este site foi profundamente inspirado pelo Refold.La, pelos trabalhos dos canais do YouTube "Matt vs. Japan" e "Stephen Kauffman", pelo trabalho de Stephen Krashen, pela minha experiência própria e pelos meus alunos e amigos.
