# O papel da gramática {-}

## Por que eu deixei a gramática por último {-}

A gramática serve para dar forma ao conteúdo. Este, por sua vez, é o que nós adquirimos por meio da imersão: toda a compreensão intuitiva que temos por conseguirmos compreender o significado e o uso de certas frases devido ao contexto em que elas se encontram.

Ora, se a gramática tem uma elevada capacidade de nos dar um melhor domínio sobre o que já compreendemos em algum nível, é claro que a imersão ajuda na compreensão da gramática.

Mas pode a gramática ajudar na compreensão do conteúdo no qual nos imergimos? Certamente. Mas a gramática, no tocante à habilidade de falar e escrever na língua, serve muito mais como uma ferramenta crítica e corretiva do que criativa. Isso é muito bom para editar um texto, mas não para escrevê-lo.^[Pode parecer uma contradição, mas _escrever_ e _editar_ são processos diferentes. A edição é um processo de crítica do que foi escrito; é onde você refina, conserta e critica. A gramática tem esse valor. Se você quiser "refinar, consertar e criticar" a sua fala em tempo real, o resultado é que você se verá calculando, gaguejando e fazendo longas pausas, o que é indesejado para muitos aprendizes de línguas estrangeiras.] A gramática é muito bom para formatar, mas para dar forma a algo, é necessário primeiro _ter algo_ a que dar forma. Quanto mais cedo a gramática é inserida[^Se o intuito de estudá-la é aprender uma nova língua.], menor o custo-benefício.

O problema é que estudar gramática requer um esforço muito maior do que a imersão por si própria, e o ganho obtido com a imersão, ao meu ver, é maior do que o ganho obtido com o estudo da gramática. Deixe-me repetir: _certamente_ estudar gramática auxiliará na nossa compreensão durante as práticas de imersão. Contudo, quando o objetivo é a aquisição, a imersão é a _via direta_. A gramática é portanto uma via indireta. Ela funciona muito como um suporte que nos ajuda na busca, mas não é ela mesma a busca. Pouco se encontra na gramática: ela só explica o que já foi encontrado, ou nos ajuda a compreender um pouco mais o que encontramos. Uma leitura mais esforçada e deliberada, e a meditação sobre certas regras a partir da nossa experiência, pode com frequência nos ajudar a preencher esse tipo de lacuna.

Por que eu acho tão importante frisar isso aqui? Porque existe um preconceito corrente na mente de estudantes e professores, e inclusive entre estudantes que nunca pararam para estudar um idioma, de que o meio para aprender a falar uma língua é estudando gramática. "Se eu memorizar todas as regras, então saberei falar a língua". Muito material didático, muitas formações de professores, e muitas horas de estudantes são devotadas ao método `Gramática+Vocabulário`.

A verdade é que se nós memorizarmos o dicionário inteiro e, junto com ele, todas regras gramaticais, nós _ainda_ não saberemos falar a língua. A razão para isso é que conseguir entender e se comunicar em um idioma não é idêntico a conhecer todas as palavras e todas as regras, mas sim a saber como as palavras e as regras dançam juntas -- e elas fazem isso de muitas e muitas formas, por vezes até mesmo contraditórias.

É um conhecimento intuitivo. Como eu falei algumas páginas atrás, _é um gingado_. E esse gingado só se adquire através da experiência e da experimentação. O dicionário e a gramática não são idênticos à língua. Eles são partes, e o todo é diferente da mera soma das partes. _Compreender as partes_ de forma alguma pode te prejudicar, mas não é possível ir somando um a um até chegar ao todo. Se você parar para estudar a gramática _após_ ter adquirido esse "gingado", a experiência será uma em que você se perceberá aprendendo coisas que você já sabia, mas não sabia que sabia.

Além disso, as regras das línguas não são todas documentadas. O que, você acha que pegar e ler uma gramática do início ao fim vai te familiarizar com todas as regras? Não vai! Há muitas regras que escapam os próprios gramáticos! Há regras para línguas que são faladas há séculos que estão sendo documentadas _hoje_! E mesmo assim, as pessoas falam a língua e usam essas regras corretamente sem nem saber que elas existem.^[Parte do trabalho de Noam Chomsky e seu grupo de pesquisa é encontrar e documentar regras até então ignoradas da língua inglesa.]

### Um adendo {-}

Se você estiver aprendendo uma língua antiga, como o grego ático ou o latim, aprender por imersão não será opção. Neste caso você **precisa** aprender gramática. Não tem como deixar isso para depois.

## Por que aprender gramática {-}

O propósito deste site é ensinar _como_ adquirir uma língua, como ser capaz de _falar nela_ e _compreender o que é falado_. Eu não acho que a gramática tem um lugar muito grande nesse processo, mas eu não acho que devemos deixar a gramática de lado. Eu não sou contra a gramática, apenas acredito que o papel dela seja outro. É um papel **muito** importante, e eu diria até mais importante do que o da aquisição. Não obstante, é ainda assim **outro** papel.

Há duas grandes vantagens para estudar gramática. A primeira delas é aperfeiçoar a nossa compreensão _sobre a_ língua. Quando aprendemos a língua por imersão, nós adquirimos uma compreensão intuitiva das regras, e pode acontecer que nós vacilemos aqui e ali na hora de nos expressarmos; pode ser que a nossa estrutura esteja um pouco cambaleante. Assim, a gramática pode servir para _aperfeiçoar_ a nossa compreensão _sobre a_ língua e, principalmente, tornar o edifício da nossa compreensão do idioma mais sólido. O que ela nos dá é mais segurança. Após termos feito uma escultura de argila ela se mostra maleável. Essa maleabilidade pode ser por vezes indesejada, e então a gramática opera como o forno que dá firmeza à nossa construção. Repare, entretanto, que aqui nós _já temos_ algo construído: queremos apenas torná-lo mais firme.[^Mesmo nestes casos, quando a estrutura cambaleia, insisto que quando o nosso desejo é aperfeiçoar a nossa produção e criatividade _com fluência_ o melhor procedimento é _mais imersão_. O poder da gramática aqui não é o de falarmos espontaneamente com maior graça e de forma mais correta, mas sim a capacidade de criticarmos melhor o que produzimos. Podemos perceber melhor os nossos erros de fala e editar melhor os nossos textos. Se quisermos corrigir esses vícios que ocorrem no momento da saída, entretanto, temos que ler e que ouvir mais.]

A segunda vantagem em estudar gramática é aperfeiçoar a nossa retórica e a nossa precisão. Isso pode parecer idêntico à primeira vantagem, mas a diferença é sutil. A primeira vantagem citada tem a ver com _segurança_, enquanto essa tem a ver com _intenção_. Compreender mais sobre a gramática da nossa língua nos permite submeter a língua à lógica, o que nos permite eliminar a ambiguidade, ou ser ambíguo de propósito.

Conhecer gramática, portanto, não se reduz a aprender a língua. A sua utilidade tem a ver com espremer dela as suas capacidades mais específicas e ocultas, e que são as últimas a serem conhecidas. A dominar os detalhes. Tem a ver com organizar os próprios pensamentos e a ser adequadamente eloquente.

Língua não é só uma forma de emitir e receber informações, mas uma forma de agir no mundo. Compreender gramática pode nos ajudar a ser mais deliberados na forma como tomamos parte nessas ações. Portanto, não despreze a gramática. A função dela não é te fazer aprender uma língua, mas sim navegar mais eficientemente e precisamente por ela.

Se o seu intuito é aprender a falar um idioma novo, todas as regras que você precisa para conseguir isso podem ser adquiridas mais ou menos por osmose.^[Não é, ou é pouco, necessário investimento de energia para aquisição das regras no aprendizado de línguas: o simples processo de imersão e a compreensão sucessiva e crescente dos enunciados na língua nos faz gradualmente adquirir uma compreensão intuitiva das regras gramaticais envolvidas.] O simples fato de estarmos passando tempo com a língua vai nos conceder uma certa intuição acerca das regras. Só com essa osmose e a devida insistência nós podemos adquirir a capacidade de compreender textos complexos e eruditos e a entender e produzir discursos bem feitos.

Não acredito que você precise fazer isso para cada língua que você aprende. Talvez seja necessário fazê-lo caso você saiba línguas muito (muito) diferentes entre si, mas a função da gramática é simples: conectar as partes da língua entre si de forma coerente, intencional e lógica (exceto quando a intenção é, de forma deliberada, violar a lógica e a coerência). Com ela, submetemos a língua à lógica e ao mesmo obedecemos à peculiaridade do próprio sistema da língua.

## Como aprender gramática {-}

Eu acredito que o verdadeiro custo-benefício em aprender gramática está _na primeira vez em que se a aprende_. Sempre haverá ganho em fazê-lo, na língua que for, mas se você já estudou a gramática de uma língua, aprender a da segunda te dará ganhos reduzidos. Claro, se o seu intuito é ser um especialista em uma segunda língua, convém que você se aperfeiçoe no estudo da gramática da língua em questão.

Veja bem. As regras são diferentes entre as línguas porque as línguas têm capacidades diferentes. Não estou dizendo que "aprendeu uma -- aprendeu todas". Há certas estruturas que existem no inglês que não possuem análogo no russo e vice-versa. Logo, se você quer se tornar um especialista em uma língua, cabe sim que você estude ela em detalhe. Porém, há algo de comum em línguas diferentes: sob formas diferentes, elas executam funções semelhantes. 

Consideremos essas duas frases:

1. O braço dói.
2. Eu vi o seu braço.

Em russo, elas seriam respectivamente:

1. Ruka bolit. (Рука болит.)
2. Ia videl tvoyu ruku. (Я видел твою руку.)

Na primeira frase, "o braço" é "ruka". Essas duas expressões cumprem a função de "sujeito" na frase. Na segunda frase, "o seu braço" é "tvoyu ruku". Aqui, essas expressões designam o objeto da frase. 

Usando artifícios diferentes, duas línguas diferentes podem cumprir a mesma função. Usando a posição na frase e o artigo "o", no português mostramos que o assunto da primeira frase é "o braço". No russo não temos artigos; usamos em vez disso o caso nominativo (nesta palavra em questão, ele é designado pelo sufixo "-a"). Quando "o braço" é objeto, ou seja, aquilo que sofre a ação do verbo^[o que foi que eu vi? O seu braço; o seu braço sofre a ação do meu ato de ver], ele vira "ruku" -- caso acusativo, designado nesta palavra pelo sufixo "-u".

Nós não temos casos de declinação na língua portuguesa, pelo menos não da mesma forma que no russo, mas em ambas as línguas nós podemos executar essas mesmas funções: fazer de algo o assunto principal da nossa frase, e mostrar como algo sofre o efeito de uma ação. No estudo da gramática não é tanto a forma pela qual se faz isso (se com artigos e posição na frase no português ou se com sufixos no final da palavra no russo) que importa, mas sim entender essas funções a despeito da forma com a qual se as executa em qualquer língua individual. O ganho de verdade é conceitual; reside na capa de organizar o próprio pensamento e discurso com esse conhecimento.

Por isso você não deve querer simplesmente aprender "as regras da língua". Se a língua não for antiga (como falei acima), você pode adquirir essas regras mais ou menos passivamente, e então reforçá-las num segundo momento com uma gramática de referência. 

O uso corrente que usam de "aprender gramática" é "aprender regras para falar certo", e a forma como isso pode ser feito foi delineada acima. Mas, se o seu intuito é aprender a gramática "por trás" da língua, que é essa série de funções que são comuns em diferentes línguas e mais ou menos independentes delas, vale a pena que você faça um curso _de gramática_. Neste caso, acho apropriado que se faça um curso desses na própria língua portuguesa.^[Há quem diga também que estudar latim pode ser muito útil nesse âmbito (pois historicamente a gramática foi ensinada através do latim, mesmo que a sua língua nativa fosse alemão).]

Sim, um curso especializado de gramática na língua portuguesa seria muito conveniente. Não vou apontar nenhum aqui porque não desejo fazer jabás. Uma outra forma de fazer isso é _analisando textos_ a partir de uma gramática. Neste caso, seria necessário obter uma gramática de referência ou didática e utilizar o que se aprende nela para analisar textos, ensaios, poemas, histórias e coisas do tipo.

## Resumo {-}

1. A capacidade de produzir numa língua é criativa. A gramática tal como ela é convencionalmente ensinada tem o propósito de servir como um processo de edição; ela aperfeiçoa, refina, edita.
2. Memorizar todas as regras gramaticais não é sinônimo de dominar a língua. O domínio da língua consiste em experiência e em um certo "gingado".
3. Mesmo no caso de línguas contemporâneas e atualmente em uso, não estão documentadas todas as regras.
4. O domínio da gramática, além da capacidade de aperfeiçoar o domínio das regras, serve para tornar o nosso uso dela mais deliberado e intencional.
5. O estudo da gramática é necessário e imprescindível, por motivos práticos, quando o nosso intuito for aprender uma língua antiga, como grego ou latim.
6. O ouro por trás do estudo da gramática não está no aperfeiçoamento e refinamento da produção linguística, mas na compreensão das funções conceituais que estão por trás das formas que são particulares a cada língua.
7. Propõe-se aqui duas formas de aprender gramática: fazer um curso especializado de gramática na língua portuguesa _e/ou_ separar textos e poemas de acordo com uma gramática de referência ou didática. Uma terceira alternativa (vide notas de rodapé da página) é estudar latim; essa é uma prática com certo valor histórico.^[Pessoalmente, estudei muito pouco de gramática latina, mas o pouco de estudo que eu tive me ajudou a compreender melhor o russo, o português e o inglês.]
