# Sobre {-}

## Sobre este site 

Não fui eu que inventei este método. Há décadas ele é trabalhado e divulgado por pesquisadores e professores como Stephen Krashen. Em outros países, há pessoas de fora das universidades que também falam abertamente a respeito desta forma de aprender. Mesmo no Brasil eu não sou o primeiro a divulgá-lo.

Mas nem todo mundo tem acesso ao material em inglês acerca deste tema. Em Português, o material acerca deste tema me parece desorganizado e espalhado. Organizar o material que eu julgo necessário para o aprendizado de línguas em um único lugar é o motivo por trás deste website.

Por que eu quis fazer isso? Porque inúmeras vezes eu estive com pessoas que demonstraram interesse em aprender línguas, e eu não tinha nenhuma referência que eu pudesse enviar para elas e dizer: "aqui está tudo o que você precisa saber". Isso me incomodava. Portanto, eis o site. 

Este site foi profundamente inspirado pelo Refold.La, pelo trabalho do autor do canal do YouTube "Matt vs. Japan", pelo trabalho de Stephen Krashen, pela minha experiência própria e pelos meus alunos e amigos.

## Sobre o autor

Meu nome é [Paulo](https://www.instagram.com/prss.alves). Sou psicólogo formado pela UERJ e tenho dado aulas de inglês desde 2016, tanto em curso quanto como professor particular. Atuo como psicoterapeuta, psicometrista e dou aulas particulares de inglês.

Além disso, há anos nutro o gosto por aprender línguas por conta própria, por prazer. Além do inglês, que aprendi usando este mesmo método que aqui divulgo, e no qual tenho um certificado nível C2 (o maior nível possível de acordo com a CEFR), também me aventurei pelas seguintes línguas: russo, francês, espanhol, grego antigo, hebraico, latim. Em russo eu consigo me comunicar razoavelmente; espanhol todo brasileiro domínio na forma de "portunhol", mas consigo ler textos clássicos na língua. Francês só me serve pra ler também. Quanto às outras três (grego, latim e hebraico), eu só consigo ler textos religiosos. Sei falar algumas frases que aprendi por repetição.

O conteúdo deste website me é caro. Eu gosto de aprender e de ensinar línguas, portanto é importante para mim que o método que exponho por meio dele seja verdadeiramente eficiente. Não acho que ele é exaustivo, mas acredito que ele possa servir como diretriz de algum modo.
