# Sobre {-}

## Sobre este site  {-}

Não fui eu que inventei este método. Há décadas ele é trabalhado e divulgado por pesquisadores e professores como Stephen Krashen. Em outros países, há pessoas de fora das universidades que também falam abertamente a respeito desta forma de aprender. Mesmo no Brasil eu não sou o primeiro a divulgá-lo.

Mas nem todo mundo tem acesso ao material em inglês acerca deste tema. Em Português, o material acerca deste tema me parece desorganizado e espalhado. Organizar o material que eu julgo necessário para o aprendizado de línguas em um único lugar é o motivo por trás deste website.

Por que eu quis fazer isso? Porque inúmeras vezes eu estive com pessoas que demonstraram interesse em aprender línguas, e eu não tinha nenhuma referência que eu pudesse enviar para elas e dizer: "aqui está tudo o que você precisa saber". Isso me incomodava. Portanto, eis o site. 

Este site foi profundamente inspirado pelo Refold.La, pelo trabalho do autor do canal do YouTube "Matt vs. Japan", pelo trabalho de Stephen Krashen, pela minha experiência própria e pelos meus alunos e amigos.

### Sobre o nome do site {-}

"Irídula" é uma palavra que consta no primeiro canto do poema "Fogo pálido" de Nabokov... e em mais nenhum outro lugar. Não existe em nenhum dicionário. Ainda assim, pelo contexto e pela descrição que ele faz dela, acredito ser perfeitamente possível compreender o seu significado. Portanto, ela serve de um bom exemplo de "aprendizado por contexto", que é boa parte do cerne deste website. Segue o trecho:

>Meu livro de figuras era o forro
>
Que envolve nossa jaula: arroxeados
>
Anéis cercando a lua, o sol em fogo
>
Cor de sangue; o arco íris geminado
>
Ou **uma irídula**, tão bela e rara,
>
Que ocorre em céu azul sobre as montanhas
>
Quando uma nuvem oval, da cor de opala,
>
Espelha a refração da tempestade
>
Que cai talvez num longínquo vale.
>
Pois mão de artista em jaula nos prendeu...

## Sobre o autor {-}

Meu nome é [Paulo](https://www.instagram.com/paulorssalves). Sou psicólogo formado pela UERJ e tenho dado aulas de inglês desde 2016, tanto em curso quanto como professor particular. Atualmente (2024) atuo como psicoterapeuta e faço mestrado em Psicologia Social.

Além disso, há anos nutro o gosto por aprender línguas por conta própria, por prazer. Além do inglês, que aprendi usando este mesmo método que aqui divulgo, e no qual tenho um certificado nível C2 (o maior nível possível de acordo com a CEFR), também me aventurei por outras línguas. Consigo me virar no russo, ler textos, contemporâneos e clássicos, e segurar uma conversa, embora não consiga falar de temas complexos. Também me enveredei pelo pelo hebraico e ainda hoje me esforço para melhorar a minha compreensão do grego antigo. Consigo também ler francês, mas não consigo falar.

O conteúdo deste website me é caro. A informação que eu coloco aqui é algo que eu uso rotineiramente na minah vida. Não acho, entretanto, que ele é exaustivo, mas acredito que ele possa servir como diretriz de algum modo.
